// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.4
// source: backup.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BackupService_RecoverMPCShare_FullMethodName  = "/infra.v1.BackupService/RecoverMPCShare"
	BackupService_GetBackupStatus_FullMethodName  = "/infra.v1.BackupService/GetBackupStatus"
	BackupService_ListBackupShares_FullMethodName = "/infra.v1.BackupService/ListBackupShares"
)

// BackupServiceClient is the client API for BackupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BackupService 备份服务
type BackupServiceClient interface {
	// 恢复MPC分片（从SSS备份分片）
	RecoverMPCShare(ctx context.Context, in *RecoverMPCShareRequest, opts ...grpc.CallOption) (*RecoverMPCShareResponse, error)
	// 获取备份状态
	GetBackupStatus(ctx context.Context, in *GetBackupStatusRequest, opts ...grpc.CallOption) (*GetBackupStatusResponse, error)
	// 列出备份分片
	ListBackupShares(ctx context.Context, in *ListBackupSharesRequest, opts ...grpc.CallOption) (*ListBackupSharesResponse, error)
}

type backupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBackupServiceClient(cc grpc.ClientConnInterface) BackupServiceClient {
	return &backupServiceClient{cc}
}

func (c *backupServiceClient) RecoverMPCShare(ctx context.Context, in *RecoverMPCShareRequest, opts ...grpc.CallOption) (*RecoverMPCShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecoverMPCShareResponse)
	err := c.cc.Invoke(ctx, BackupService_RecoverMPCShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) GetBackupStatus(ctx context.Context, in *GetBackupStatusRequest, opts ...grpc.CallOption) (*GetBackupStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBackupStatusResponse)
	err := c.cc.Invoke(ctx, BackupService_GetBackupStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) ListBackupShares(ctx context.Context, in *ListBackupSharesRequest, opts ...grpc.CallOption) (*ListBackupSharesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBackupSharesResponse)
	err := c.cc.Invoke(ctx, BackupService_ListBackupShares_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackupServiceServer is the server API for BackupService service.
// All implementations must embed UnimplementedBackupServiceServer
// for forward compatibility.
//
// BackupService 备份服务
type BackupServiceServer interface {
	// 恢复MPC分片（从SSS备份分片）
	RecoverMPCShare(context.Context, *RecoverMPCShareRequest) (*RecoverMPCShareResponse, error)
	// 获取备份状态
	GetBackupStatus(context.Context, *GetBackupStatusRequest) (*GetBackupStatusResponse, error)
	// 列出备份分片
	ListBackupShares(context.Context, *ListBackupSharesRequest) (*ListBackupSharesResponse, error)
	mustEmbedUnimplementedBackupServiceServer()
}

// UnimplementedBackupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackupServiceServer struct{}

func (UnimplementedBackupServiceServer) RecoverMPCShare(context.Context, *RecoverMPCShareRequest) (*RecoverMPCShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecoverMPCShare not implemented")
}
func (UnimplementedBackupServiceServer) GetBackupStatus(context.Context, *GetBackupStatusRequest) (*GetBackupStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBackupStatus not implemented")
}
func (UnimplementedBackupServiceServer) ListBackupShares(context.Context, *ListBackupSharesRequest) (*ListBackupSharesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBackupShares not implemented")
}
func (UnimplementedBackupServiceServer) mustEmbedUnimplementedBackupServiceServer() {}
func (UnimplementedBackupServiceServer) testEmbeddedByValue()                       {}

// UnsafeBackupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackupServiceServer will
// result in compilation errors.
type UnsafeBackupServiceServer interface {
	mustEmbedUnimplementedBackupServiceServer()
}

func RegisterBackupServiceServer(s grpc.ServiceRegistrar, srv BackupServiceServer) {
	// If the following call panics, it indicates UnimplementedBackupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BackupService_ServiceDesc, srv)
}

func _BackupService_RecoverMPCShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverMPCShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).RecoverMPCShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_RecoverMPCShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).RecoverMPCShare(ctx, req.(*RecoverMPCShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_GetBackupStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBackupStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).GetBackupStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_GetBackupStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).GetBackupStatus(ctx, req.(*GetBackupStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_ListBackupShares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBackupSharesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).ListBackupShares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_ListBackupShares_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).ListBackupShares(ctx, req.(*ListBackupSharesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackupService_ServiceDesc is the grpc.ServiceDesc for BackupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infra.v1.BackupService",
	HandlerType: (*BackupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecoverMPCShare",
			Handler:    _BackupService_RecoverMPCShare_Handler,
		},
		{
			MethodName: "GetBackupStatus",
			Handler:    _BackupService_GetBackupStatus_Handler,
		},
		{
			MethodName: "ListBackupShares",
			Handler:    _BackupService_ListBackupShares_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backup.proto",
}

const (
	BackupDeliveryService_RequestShareDelivery_FullMethodName = "/infra.v1.BackupDeliveryService/RequestShareDelivery"
	BackupDeliveryService_ConfirmShareDelivery_FullMethodName = "/infra.v1.BackupDeliveryService/ConfirmShareDelivery"
	BackupDeliveryService_QueryShareStatus_FullMethodName     = "/infra.v1.BackupDeliveryService/QueryShareStatus"
)

// BackupDeliveryServiceClient is the client API for BackupDeliveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BackupDeliveryService 备份分片下发服务
type BackupDeliveryServiceClient interface {
	// 请求分片下发
	RequestShareDelivery(ctx context.Context, in *ShareDeliveryRequest, opts ...grpc.CallOption) (*ShareDeliveryResponse, error)
	// 确认分片接收
	ConfirmShareDelivery(ctx context.Context, in *ShareConfirmationRequest, opts ...grpc.CallOption) (*ShareConfirmationResponse, error)
	// 查询分片状态
	QueryShareStatus(ctx context.Context, in *ShareStatusQuery, opts ...grpc.CallOption) (*ShareStatusResponse, error)
}

type backupDeliveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBackupDeliveryServiceClient(cc grpc.ClientConnInterface) BackupDeliveryServiceClient {
	return &backupDeliveryServiceClient{cc}
}

func (c *backupDeliveryServiceClient) RequestShareDelivery(ctx context.Context, in *ShareDeliveryRequest, opts ...grpc.CallOption) (*ShareDeliveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShareDeliveryResponse)
	err := c.cc.Invoke(ctx, BackupDeliveryService_RequestShareDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupDeliveryServiceClient) ConfirmShareDelivery(ctx context.Context, in *ShareConfirmationRequest, opts ...grpc.CallOption) (*ShareConfirmationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShareConfirmationResponse)
	err := c.cc.Invoke(ctx, BackupDeliveryService_ConfirmShareDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupDeliveryServiceClient) QueryShareStatus(ctx context.Context, in *ShareStatusQuery, opts ...grpc.CallOption) (*ShareStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShareStatusResponse)
	err := c.cc.Invoke(ctx, BackupDeliveryService_QueryShareStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackupDeliveryServiceServer is the server API for BackupDeliveryService service.
// All implementations must embed UnimplementedBackupDeliveryServiceServer
// for forward compatibility.
//
// BackupDeliveryService 备份分片下发服务
type BackupDeliveryServiceServer interface {
	// 请求分片下发
	RequestShareDelivery(context.Context, *ShareDeliveryRequest) (*ShareDeliveryResponse, error)
	// 确认分片接收
	ConfirmShareDelivery(context.Context, *ShareConfirmationRequest) (*ShareConfirmationResponse, error)
	// 查询分片状态
	QueryShareStatus(context.Context, *ShareStatusQuery) (*ShareStatusResponse, error)
	mustEmbedUnimplementedBackupDeliveryServiceServer()
}

// UnimplementedBackupDeliveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackupDeliveryServiceServer struct{}

func (UnimplementedBackupDeliveryServiceServer) RequestShareDelivery(context.Context, *ShareDeliveryRequest) (*ShareDeliveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestShareDelivery not implemented")
}
func (UnimplementedBackupDeliveryServiceServer) ConfirmShareDelivery(context.Context, *ShareConfirmationRequest) (*ShareConfirmationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmShareDelivery not implemented")
}
func (UnimplementedBackupDeliveryServiceServer) QueryShareStatus(context.Context, *ShareStatusQuery) (*ShareStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryShareStatus not implemented")
}
func (UnimplementedBackupDeliveryServiceServer) mustEmbedUnimplementedBackupDeliveryServiceServer() {}
func (UnimplementedBackupDeliveryServiceServer) testEmbeddedByValue()                               {}

// UnsafeBackupDeliveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackupDeliveryServiceServer will
// result in compilation errors.
type UnsafeBackupDeliveryServiceServer interface {
	mustEmbedUnimplementedBackupDeliveryServiceServer()
}

func RegisterBackupDeliveryServiceServer(s grpc.ServiceRegistrar, srv BackupDeliveryServiceServer) {
	// If the following call panics, it indicates UnimplementedBackupDeliveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BackupDeliveryService_ServiceDesc, srv)
}

func _BackupDeliveryService_RequestShareDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareDeliveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupDeliveryServiceServer).RequestShareDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupDeliveryService_RequestShareDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupDeliveryServiceServer).RequestShareDelivery(ctx, req.(*ShareDeliveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupDeliveryService_ConfirmShareDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareConfirmationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupDeliveryServiceServer).ConfirmShareDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupDeliveryService_ConfirmShareDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupDeliveryServiceServer).ConfirmShareDelivery(ctx, req.(*ShareConfirmationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupDeliveryService_QueryShareStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareStatusQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupDeliveryServiceServer).QueryShareStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupDeliveryService_QueryShareStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupDeliveryServiceServer).QueryShareStatus(ctx, req.(*ShareStatusQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// BackupDeliveryService_ServiceDesc is the grpc.ServiceDesc for BackupDeliveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackupDeliveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infra.v1.BackupDeliveryService",
	HandlerType: (*BackupDeliveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestShareDelivery",
			Handler:    _BackupDeliveryService_RequestShareDelivery_Handler,
		},
		{
			MethodName: "ConfirmShareDelivery",
			Handler:    _BackupDeliveryService_ConfirmShareDelivery_Handler,
		},
		{
			MethodName: "QueryShareStatus",
			Handler:    _BackupDeliveryService_QueryShareStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backup.proto",
}
