// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: backup.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RecoverMPCShareRequest 恢复MPC分片请求
type RecoverMPCShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // server-proxy-1, server-proxy-2, client-{userID}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoverMPCShareRequest) Reset() {
	*x = RecoverMPCShareRequest{}
	mi := &file_backup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverMPCShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverMPCShareRequest) ProtoMessage() {}

func (x *RecoverMPCShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverMPCShareRequest.ProtoReflect.Descriptor instead.
func (*RecoverMPCShareRequest) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{0}
}

func (x *RecoverMPCShareRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *RecoverMPCShareRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// RecoverMPCShareResponse 恢复MPC分片响应
type RecoverMPCShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoverMPCShareResponse) Reset() {
	*x = RecoverMPCShareResponse{}
	mi := &file_backup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverMPCShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverMPCShareResponse) ProtoMessage() {}

func (x *RecoverMPCShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverMPCShareResponse.ProtoReflect.Descriptor instead.
func (*RecoverMPCShareResponse) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{1}
}

func (x *RecoverMPCShareResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *RecoverMPCShareResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RecoverMPCShareResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecoverMPCShareResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetBackupStatusRequest 获取备份状态请求
type GetBackupStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackupStatusRequest) Reset() {
	*x = GetBackupStatusRequest{}
	mi := &file_backup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackupStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackupStatusRequest) ProtoMessage() {}

func (x *GetBackupStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackupStatusRequest.ProtoReflect.Descriptor instead.
func (*GetBackupStatusRequest) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{2}
}

func (x *GetBackupStatusRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

// GetBackupStatusResponse 获取备份状态响应
type GetBackupStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Statuses      []*BackupStatus        `protobuf:"bytes,2,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackupStatusResponse) Reset() {
	*x = GetBackupStatusResponse{}
	mi := &file_backup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackupStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackupStatusResponse) ProtoMessage() {}

func (x *GetBackupStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackupStatusResponse.ProtoReflect.Descriptor instead.
func (*GetBackupStatusResponse) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{3}
}

func (x *GetBackupStatusResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *GetBackupStatusResponse) GetStatuses() []*BackupStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

// ListBackupSharesRequest 列出备份分片请求
type ListBackupSharesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // 可选，如果为空则列出所有节点的备份分片
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupSharesRequest) Reset() {
	*x = ListBackupSharesRequest{}
	mi := &file_backup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupSharesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupSharesRequest) ProtoMessage() {}

func (x *ListBackupSharesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupSharesRequest.ProtoReflect.Descriptor instead.
func (*ListBackupSharesRequest) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{4}
}

func (x *ListBackupSharesRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ListBackupSharesRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// ListBackupSharesResponse 列出备份分片响应
type ListBackupSharesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	KeyId         string                   `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	SharesByNode  map[string]*BackupShares `protobuf:"bytes,2,rep,name=shares_by_node,json=sharesByNode,proto3" json:"shares_by_node,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // node_id -> BackupShares
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupSharesResponse) Reset() {
	*x = ListBackupSharesResponse{}
	mi := &file_backup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupSharesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupSharesResponse) ProtoMessage() {}

func (x *ListBackupSharesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupSharesResponse.ProtoReflect.Descriptor instead.
func (*ListBackupSharesResponse) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{5}
}

func (x *ListBackupSharesResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ListBackupSharesResponse) GetSharesByNode() map[string]*BackupShares {
	if x != nil {
		return x.SharesByNode
	}
	return nil
}

// BackupStatus 备份状态
type BackupStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TotalShares    int32                  `protobuf:"varint,2,opt,name=total_shares,json=totalShares,proto3" json:"total_shares,omitempty"`
	RequiredShares int32                  `protobuf:"varint,3,opt,name=required_shares,json=requiredShares,proto3" json:"required_shares,omitempty"`
	Recoverable    bool                   `protobuf:"varint,4,opt,name=recoverable,proto3" json:"recoverable,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BackupStatus) Reset() {
	*x = BackupStatus{}
	mi := &file_backup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupStatus) ProtoMessage() {}

func (x *BackupStatus) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupStatus.ProtoReflect.Descriptor instead.
func (*BackupStatus) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{6}
}

func (x *BackupStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *BackupStatus) GetTotalShares() int32 {
	if x != nil {
		return x.TotalShares
	}
	return 0
}

func (x *BackupStatus) GetRequiredShares() int32 {
	if x != nil {
		return x.RequiredShares
	}
	return 0
}

func (x *BackupStatus) GetRecoverable() bool {
	if x != nil {
		return x.Recoverable
	}
	return false
}

// BackupShares 备份分片列表
type BackupShares struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Shares        []*BackupShare         `protobuf:"bytes,2,rep,name=shares,proto3" json:"shares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupShares) Reset() {
	*x = BackupShares{}
	mi := &file_backup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupShares) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupShares) ProtoMessage() {}

func (x *BackupShares) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupShares.ProtoReflect.Descriptor instead.
func (*BackupShares) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{7}
}

func (x *BackupShares) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *BackupShares) GetShares() []*BackupShare {
	if x != nil {
		return x.Shares
	}
	return nil
}

// BackupShare 备份分片
type BackupShare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ShareIndex    int32                  `protobuf:"varint,3,opt,name=share_index,json=shareIndex,proto3" json:"share_index,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupShare) Reset() {
	*x = BackupShare{}
	mi := &file_backup_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupShare) ProtoMessage() {}

func (x *BackupShare) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupShare.ProtoReflect.Descriptor instead.
func (*BackupShare) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{8}
}

func (x *BackupShare) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *BackupShare) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *BackupShare) GetShareIndex() int32 {
	if x != nil {
		return x.ShareIndex
	}
	return 0
}

func (x *BackupShare) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ShareDeliveryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientId        string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // UserID
	KeyId           string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	NodeId          string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ShareIndex      int32                  `protobuf:"varint,4,opt,name=share_index,json=shareIndex,proto3" json:"share_index,omitempty"`
	ClientPublicKey []byte                 `protobuf:"bytes,5,opt,name=client_public_key,json=clientPublicKey,proto3" json:"client_public_key,omitempty"` // 客户端公钥 (for encryption)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ShareDeliveryRequest) Reset() {
	*x = ShareDeliveryRequest{}
	mi := &file_backup_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareDeliveryRequest) ProtoMessage() {}

func (x *ShareDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareDeliveryRequest.ProtoReflect.Descriptor instead.
func (*ShareDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{9}
}

func (x *ShareDeliveryRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ShareDeliveryRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ShareDeliveryRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ShareDeliveryRequest) GetShareIndex() int32 {
	if x != nil {
		return x.ShareIndex
	}
	return 0
}

func (x *ShareDeliveryRequest) GetClientPublicKey() []byte {
	if x != nil {
		return x.ClientPublicKey
	}
	return nil
}

type ShareDeliveryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// delivery_id removed as we use composite key
	EncryptedShare []byte `protobuf:"bytes,2,opt,name=encrypted_share,json=encryptedShare,proto3" json:"encrypted_share,omitempty"`
	Signature      []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"` // 服务端签名
	Timestamp      int64  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShareDeliveryResponse) Reset() {
	*x = ShareDeliveryResponse{}
	mi := &file_backup_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareDeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareDeliveryResponse) ProtoMessage() {}

func (x *ShareDeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareDeliveryResponse.ProtoReflect.Descriptor instead.
func (*ShareDeliveryResponse) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{10}
}

func (x *ShareDeliveryResponse) GetEncryptedShare() []byte {
	if x != nil {
		return x.EncryptedShare
	}
	return nil
}

func (x *ShareDeliveryResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ShareDeliveryResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ShareConfirmationRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ClientId             string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // UserID
	KeyId                string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	NodeId               string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ShareIndex           int32                  `protobuf:"varint,4,opt,name=share_index,json=shareIndex,proto3" json:"share_index,omitempty"`
	ReceivedSuccessfully bool                   `protobuf:"varint,5,opt,name=received_successfully,json=receivedSuccessfully,proto3" json:"received_successfully,omitempty"`
	FailureReason        string                 `protobuf:"bytes,6,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ShareConfirmationRequest) Reset() {
	*x = ShareConfirmationRequest{}
	mi := &file_backup_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareConfirmationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareConfirmationRequest) ProtoMessage() {}

func (x *ShareConfirmationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareConfirmationRequest.ProtoReflect.Descriptor instead.
func (*ShareConfirmationRequest) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{11}
}

func (x *ShareConfirmationRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ShareConfirmationRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ShareConfirmationRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ShareConfirmationRequest) GetShareIndex() int32 {
	if x != nil {
		return x.ShareIndex
	}
	return 0
}

func (x *ShareConfirmationRequest) GetReceivedSuccessfully() bool {
	if x != nil {
		return x.ReceivedSuccessfully
	}
	return false
}

func (x *ShareConfirmationRequest) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

type ShareConfirmationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confirmed     bool                   `protobuf:"varint,1,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareConfirmationResponse) Reset() {
	*x = ShareConfirmationResponse{}
	mi := &file_backup_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareConfirmationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareConfirmationResponse) ProtoMessage() {}

func (x *ShareConfirmationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareConfirmationResponse.ProtoReflect.Descriptor instead.
func (*ShareConfirmationResponse) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{12}
}

func (x *ShareConfirmationResponse) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

func (x *ShareConfirmationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ShareStatusQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // UserID
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ShareIndex    int32                  `protobuf:"varint,4,opt,name=share_index,json=shareIndex,proto3" json:"share_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareStatusQuery) Reset() {
	*x = ShareStatusQuery{}
	mi := &file_backup_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareStatusQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareStatusQuery) ProtoMessage() {}

func (x *ShareStatusQuery) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareStatusQuery.ProtoReflect.Descriptor instead.
func (*ShareStatusQuery) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{13}
}

func (x *ShareStatusQuery) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ShareStatusQuery) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ShareStatusQuery) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ShareStatusQuery) GetShareIndex() int32 {
	if x != nil {
		return x.ShareIndex
	}
	return 0
}

type ShareStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	DeliveredAt   int64                  `protobuf:"varint,2,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	ConfirmedAt   int64                  `protobuf:"varint,3,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`
	FailureReason string                 `protobuf:"bytes,4,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareStatusResponse) Reset() {
	*x = ShareStatusResponse{}
	mi := &file_backup_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareStatusResponse) ProtoMessage() {}

func (x *ShareStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backup_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareStatusResponse.ProtoReflect.Descriptor instead.
func (*ShareStatusResponse) Descriptor() ([]byte, []int) {
	return file_backup_proto_rawDescGZIP(), []int{14}
}

func (x *ShareStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ShareStatusResponse) GetDeliveredAt() int64 {
	if x != nil {
		return x.DeliveredAt
	}
	return 0
}

func (x *ShareStatusResponse) GetConfirmedAt() int64 {
	if x != nil {
		return x.ConfirmedAt
	}
	return 0
}

func (x *ShareStatusResponse) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

var File_backup_proto protoreflect.FileDescriptor

const file_backup_proto_rawDesc = "" +
	"\n" +
	"\fbackup.proto\x12\binfra.v1\x1a\fcommon.proto\"H\n" +
	"\x16RecoverMPCShareRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"}\n" +
	"\x17RecoverMPCShareResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"/\n" +
	"\x16GetBackupStatusRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\"d\n" +
	"\x17GetBackupStatusResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x122\n" +
	"\bstatuses\x18\x02 \x03(\v2\x16.infra.v1.BackupStatusR\bstatuses\"I\n" +
	"\x17ListBackupSharesRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"\xe6\x01\n" +
	"\x18ListBackupSharesResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12Z\n" +
	"\x0eshares_by_node\x18\x02 \x03(\v24.infra.v1.ListBackupSharesResponse.SharesByNodeEntryR\fsharesByNode\x1aW\n" +
	"\x11SharesByNodeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.infra.v1.BackupSharesR\x05value:\x028\x01\"\x95\x01\n" +
	"\fBackupStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\ftotal_shares\x18\x02 \x01(\x05R\vtotalShares\x12'\n" +
	"\x0frequired_shares\x18\x03 \x01(\x05R\x0erequiredShares\x12 \n" +
	"\vrecoverable\x18\x04 \x01(\bR\vrecoverable\"V\n" +
	"\fBackupShares\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12-\n" +
	"\x06shares\x18\x02 \x03(\v2\x15.infra.v1.BackupShareR\x06shares\"}\n" +
	"\vBackupShare\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vshare_index\x18\x03 \x01(\x05R\n" +
	"shareIndex\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"\xb0\x01\n" +
	"\x14ShareDeliveryRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vshare_index\x18\x04 \x01(\x05R\n" +
	"shareIndex\x12*\n" +
	"\x11client_public_key\x18\x05 \x01(\fR\x0fclientPublicKey\"|\n" +
	"\x15ShareDeliveryResponse\x12'\n" +
	"\x0fencrypted_share\x18\x02 \x01(\fR\x0eencryptedShare\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\xe4\x01\n" +
	"\x18ShareConfirmationRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vshare_index\x18\x04 \x01(\x05R\n" +
	"shareIndex\x123\n" +
	"\x15received_successfully\x18\x05 \x01(\bR\x14receivedSuccessfully\x12%\n" +
	"\x0efailure_reason\x18\x06 \x01(\tR\rfailureReason\"S\n" +
	"\x19ShareConfirmationResponse\x12\x1c\n" +
	"\tconfirmed\x18\x01 \x01(\bR\tconfirmed\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x80\x01\n" +
	"\x10ShareStatusQuery\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vshare_index\x18\x04 \x01(\x05R\n" +
	"shareIndex\"\x9a\x01\n" +
	"\x13ShareStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12!\n" +
	"\fdelivered_at\x18\x02 \x01(\x03R\vdeliveredAt\x12!\n" +
	"\fconfirmed_at\x18\x03 \x01(\x03R\vconfirmedAt\x12%\n" +
	"\x0efailure_reason\x18\x04 \x01(\tR\rfailureReason2\x9a\x02\n" +
	"\rBackupService\x12V\n" +
	"\x0fRecoverMPCShare\x12 .infra.v1.RecoverMPCShareRequest\x1a!.infra.v1.RecoverMPCShareResponse\x12V\n" +
	"\x0fGetBackupStatus\x12 .infra.v1.GetBackupStatusRequest\x1a!.infra.v1.GetBackupStatusResponse\x12Y\n" +
	"\x10ListBackupShares\x12!.infra.v1.ListBackupSharesRequest\x1a\".infra.v1.ListBackupSharesResponse2\xa0\x02\n" +
	"\x15BackupDeliveryService\x12W\n" +
	"\x14RequestShareDelivery\x12\x1e.infra.v1.ShareDeliveryRequest\x1a\x1f.infra.v1.ShareDeliveryResponse\x12_\n" +
	"\x14ConfirmShareDelivery\x12\".infra.v1.ShareConfirmationRequest\x1a#.infra.v1.ShareConfirmationResponse\x12M\n" +
	"\x10QueryShareStatus\x12\x1a.infra.v1.ShareStatusQuery\x1a\x1d.infra.v1.ShareStatusResponseB9Z7github.com/kashguard/go-mpc-wallet/internal/pb/infra/v1b\x06proto3"

var (
	file_backup_proto_rawDescOnce sync.Once
	file_backup_proto_rawDescData []byte
)

func file_backup_proto_rawDescGZIP() []byte {
	file_backup_proto_rawDescOnce.Do(func() {
		file_backup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backup_proto_rawDesc), len(file_backup_proto_rawDesc)))
	})
	return file_backup_proto_rawDescData
}

var file_backup_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_backup_proto_goTypes = []any{
	(*RecoverMPCShareRequest)(nil),    // 0: infra.v1.RecoverMPCShareRequest
	(*RecoverMPCShareResponse)(nil),   // 1: infra.v1.RecoverMPCShareResponse
	(*GetBackupStatusRequest)(nil),    // 2: infra.v1.GetBackupStatusRequest
	(*GetBackupStatusResponse)(nil),   // 3: infra.v1.GetBackupStatusResponse
	(*ListBackupSharesRequest)(nil),   // 4: infra.v1.ListBackupSharesRequest
	(*ListBackupSharesResponse)(nil),  // 5: infra.v1.ListBackupSharesResponse
	(*BackupStatus)(nil),              // 6: infra.v1.BackupStatus
	(*BackupShares)(nil),              // 7: infra.v1.BackupShares
	(*BackupShare)(nil),               // 8: infra.v1.BackupShare
	(*ShareDeliveryRequest)(nil),      // 9: infra.v1.ShareDeliveryRequest
	(*ShareDeliveryResponse)(nil),     // 10: infra.v1.ShareDeliveryResponse
	(*ShareConfirmationRequest)(nil),  // 11: infra.v1.ShareConfirmationRequest
	(*ShareConfirmationResponse)(nil), // 12: infra.v1.ShareConfirmationResponse
	(*ShareStatusQuery)(nil),          // 13: infra.v1.ShareStatusQuery
	(*ShareStatusResponse)(nil),       // 14: infra.v1.ShareStatusResponse
	nil,                               // 15: infra.v1.ListBackupSharesResponse.SharesByNodeEntry
}
var file_backup_proto_depIdxs = []int32{
	6,  // 0: infra.v1.GetBackupStatusResponse.statuses:type_name -> infra.v1.BackupStatus
	15, // 1: infra.v1.ListBackupSharesResponse.shares_by_node:type_name -> infra.v1.ListBackupSharesResponse.SharesByNodeEntry
	8,  // 2: infra.v1.BackupShares.shares:type_name -> infra.v1.BackupShare
	7,  // 3: infra.v1.ListBackupSharesResponse.SharesByNodeEntry.value:type_name -> infra.v1.BackupShares
	0,  // 4: infra.v1.BackupService.RecoverMPCShare:input_type -> infra.v1.RecoverMPCShareRequest
	2,  // 5: infra.v1.BackupService.GetBackupStatus:input_type -> infra.v1.GetBackupStatusRequest
	4,  // 6: infra.v1.BackupService.ListBackupShares:input_type -> infra.v1.ListBackupSharesRequest
	9,  // 7: infra.v1.BackupDeliveryService.RequestShareDelivery:input_type -> infra.v1.ShareDeliveryRequest
	11, // 8: infra.v1.BackupDeliveryService.ConfirmShareDelivery:input_type -> infra.v1.ShareConfirmationRequest
	13, // 9: infra.v1.BackupDeliveryService.QueryShareStatus:input_type -> infra.v1.ShareStatusQuery
	1,  // 10: infra.v1.BackupService.RecoverMPCShare:output_type -> infra.v1.RecoverMPCShareResponse
	3,  // 11: infra.v1.BackupService.GetBackupStatus:output_type -> infra.v1.GetBackupStatusResponse
	5,  // 12: infra.v1.BackupService.ListBackupShares:output_type -> infra.v1.ListBackupSharesResponse
	10, // 13: infra.v1.BackupDeliveryService.RequestShareDelivery:output_type -> infra.v1.ShareDeliveryResponse
	12, // 14: infra.v1.BackupDeliveryService.ConfirmShareDelivery:output_type -> infra.v1.ShareConfirmationResponse
	14, // 15: infra.v1.BackupDeliveryService.QueryShareStatus:output_type -> infra.v1.ShareStatusResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_backup_proto_init() }
func file_backup_proto_init() {
	if File_backup_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backup_proto_rawDesc), len(file_backup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_backup_proto_goTypes,
		DependencyIndexes: file_backup_proto_depIdxs,
		MessageInfos:      file_backup_proto_msgTypes,
	}.Build()
	File_backup_proto = out.File
	file_backup_proto_goTypes = nil
	file_backup_proto_depIdxs = nil
}
