// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: mpc/v1/mpc.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 会话相关消息
type CreateSessionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	KeyId            string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Message          []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Protocol         string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"` // "gg18", "gg20", "frost"
	TimeoutSeconds   int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	ParticipantNodes []string               `protobuf:"bytes,5,rep,name=participant_nodes,json=participantNodes,proto3" json:"participant_nodes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *CreateSessionRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *CreateSessionRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *CreateSessionRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *CreateSessionRequest) GetParticipantNodes() []string {
	if x != nil {
		return x.ParticipantNodes
	}
	return nil
}

type CreateSessionResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionId          string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Threshold          int32                  `protobuf:"varint,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	TotalNodes         int32                  `protobuf:"varint,4,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	ParticipatingNodes []string               `protobuf:"bytes,5,rep,name=participating_nodes,json=participatingNodes,proto3" json:"participating_nodes,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt          string                 `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateSessionResponse) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *CreateSessionResponse) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *CreateSessionResponse) GetParticipatingNodes() []string {
	if x != nil {
		return x.ParticipatingNodes
	}
	return nil
}

func (x *CreateSessionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateSessionResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type SessionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStatusRequest) Reset() {
	*x = SessionStatusRequest{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatusRequest) ProtoMessage() {}

func (x *SessionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatusRequest.ProtoReflect.Descriptor instead.
func (*SessionStatusRequest) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{2}
}

func (x *SessionStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionStatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionId          string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CurrentRound       int32                  `protobuf:"varint,3,opt,name=current_round,json=currentRound,proto3" json:"current_round,omitempty"`
	TotalRounds        int32                  `protobuf:"varint,4,opt,name=total_rounds,json=totalRounds,proto3" json:"total_rounds,omitempty"`
	ParticipatingNodes []string               `protobuf:"bytes,5,rep,name=participating_nodes,json=participatingNodes,proto3" json:"participating_nodes,omitempty"`
	Signature          string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"` // hex encoded
	CreatedAt          string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt        string                 `protobuf:"bytes,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	DurationMs         int32                  `protobuf:"varint,9,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SessionStatusResponse) Reset() {
	*x = SessionStatusResponse{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatusResponse) ProtoMessage() {}

func (x *SessionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatusResponse.ProtoReflect.Descriptor instead.
func (*SessionStatusResponse) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{3}
}

func (x *SessionStatusResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionStatusResponse) GetCurrentRound() int32 {
	if x != nil {
		return x.CurrentRound
	}
	return 0
}

func (x *SessionStatusResponse) GetTotalRounds() int32 {
	if x != nil {
		return x.TotalRounds
	}
	return 0
}

func (x *SessionStatusResponse) GetParticipatingNodes() []string {
	if x != nil {
		return x.ParticipatingNodes
	}
	return nil
}

func (x *SessionStatusResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SessionStatusResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SessionStatusResponse) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *SessionStatusResponse) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// 签名分片相关消息
type ShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ShareData     []byte                 `protobuf:"bytes,3,opt,name=share_data,json=shareData,proto3" json:"share_data,omitempty"`
	Round         int32                  `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareRequest) Reset() {
	*x = ShareRequest{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareRequest) ProtoMessage() {}

func (x *ShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareRequest.ProtoReflect.Descriptor instead.
func (*ShareRequest) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{4}
}

func (x *ShareRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ShareRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ShareRequest) GetShareData() []byte {
	if x != nil {
		return x.ShareData
	}
	return nil
}

func (x *ShareRequest) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *ShareRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type ShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NextRound     int32                  `protobuf:"varint,3,opt,name=next_round,json=nextRound,proto3" json:"next_round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareResponse) Reset() {
	*x = ShareResponse{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareResponse) ProtoMessage() {}

func (x *ShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareResponse.ProtoReflect.Descriptor instead.
func (*ShareResponse) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{5}
}

func (x *ShareResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ShareResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ShareResponse) GetNextRound() int32 {
	if x != nil {
		return x.NextRound
	}
	return 0
}

// 启动 DKG 请求/响应
type StartDKGRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // DKG 会话ID（等于 key_id）
	KeyId           string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Algorithm       string                 `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"` // 例：ECDSA
	Curve           string                 `protobuf:"bytes,4,opt,name=curve,proto3" json:"curve,omitempty"`         // 例：secp256k1
	Threshold       int32                  `protobuf:"varint,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	TotalNodes      int32                  `protobuf:"varint,6,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	NodeIds         []string               `protobuf:"bytes,8,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"` // 参与节点列表
	DerivationPath  string                 `protobuf:"bytes,9,opt,name=derivation_path,json=derivationPath,proto3" json:"derivation_path,omitempty"`
	ParentChainCode []byte                 `protobuf:"bytes,10,opt,name=parent_chain_code,json=parentChainCode,proto3" json:"parent_chain_code,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartDKGRequest) Reset() {
	*x = StartDKGRequest{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDKGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDKGRequest) ProtoMessage() {}

func (x *StartDKGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDKGRequest.ProtoReflect.Descriptor instead.
func (*StartDKGRequest) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{6}
}

func (x *StartDKGRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartDKGRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *StartDKGRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *StartDKGRequest) GetCurve() string {
	if x != nil {
		return x.Curve
	}
	return ""
}

func (x *StartDKGRequest) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *StartDKGRequest) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *StartDKGRequest) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

type StartDKGResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Started       bool                   `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartDKGResponse) Reset() {
	*x = StartDKGResponse{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDKGResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDKGResponse) ProtoMessage() {}

func (x *StartDKGResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDKGResponse.ProtoReflect.Descriptor instead.
func (*StartDKGResponse) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{7}
}

func (x *StartDKGResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *StartDKGResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 启动签名 请求/响应
type StartSignRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 签名会话ID
	KeyId           string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Message         []byte                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                         // 要签名的消息
	MessageHex      string                 `protobuf:"bytes,4,opt,name=message_hex,json=messageHex,proto3" json:"message_hex,omitempty"` // 消息的hex编码（可选）
	Protocol        string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`                       // "gg18", "gg20", "frost"
	Threshold       int32                  `protobuf:"varint,6,opt,name=threshold,proto3" json:"threshold,omitempty"`
	TotalNodes      int32                  `protobuf:"varint,7,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	NodeIds         []string               `protobuf:"bytes,8,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"` // 参与节点列表
	DerivationPath  string                 `protobuf:"bytes,9,opt,name=derivation_path,json=derivationPath,proto3" json:"derivation_path,omitempty"`
	ParentChainCode []byte                 `protobuf:"bytes,10,opt,name=parent_chain_code,json=parentChainCode,proto3" json:"parent_chain_code,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartSignRequest) Reset() {
	*x = StartSignRequest{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSignRequest) ProtoMessage() {}

func (x *StartSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSignRequest.ProtoReflect.Descriptor instead.
func (*StartSignRequest) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{8}
}

func (x *StartSignRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartSignRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *StartSignRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *StartSignRequest) GetMessageHex() string {
	if x != nil {
		return x.MessageHex
	}
	return ""
}

func (x *StartSignRequest) GetDerivationPath() string {
	if x != nil {
		return x.DerivationPath
	}
	return ""
}

func (x *StartSignRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *StartSignRequest) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *StartSignRequest) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *StartSignRequest) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

func (x *StartSignRequest) GetParentChainCode() []byte {
	if x != nil {
		return x.ParentChainCode
	}
	return nil
}

type StartSignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Started       bool                   `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSignResponse) Reset() {
	*x = StartSignResponse{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSignResponse) ProtoMessage() {}

func (x *StartSignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSignResponse.ProtoReflect.Descriptor instead.
func (*StartSignResponse) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{9}
}

func (x *StartSignResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *StartSignResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 签名聚合相关消息
type AggregateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateRequest) Reset() {
	*x = AggregateRequest{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateRequest) ProtoMessage() {}

func (x *AggregateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateRequest.ProtoReflect.Descriptor instead.
func (*AggregateRequest) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{10}
}

func (x *AggregateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AggregateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`                  // hex encoded
	PublicKey     string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // hex encoded
	MessageHash   string                 `protobuf:"bytes,4,opt,name=message_hash,json=messageHash,proto3" json:"message_hash,omitempty"`
	AggregatedAt  string                 `protobuf:"bytes,5,opt,name=aggregated_at,json=aggregatedAt,proto3" json:"aggregated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateResponse) Reset() {
	*x = AggregateResponse{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateResponse) ProtoMessage() {}

func (x *AggregateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateResponse.ProtoReflect.Descriptor instead.
func (*AggregateResponse) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{11}
}

func (x *AggregateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AggregateResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *AggregateResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *AggregateResponse) GetMessageHash() string {
	if x != nil {
		return x.MessageHash
	}
	return ""
}

func (x *AggregateResponse) GetAggregatedAt() string {
	if x != nil {
		return x.AggregatedAt
	}
	return ""
}

// 双向流消息
type SessionMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MessageType:
	//
	//	*SessionMessage_JoinRequest
	//	*SessionMessage_ShareMessage
	//	*SessionMessage_HeartbeatRequest
	//	*SessionMessage_Confirmation
	//	*SessionMessage_RoundMessage
	//	*SessionMessage_CompletionMessage
	//	*SessionMessage_ErrorMessage
	MessageType   isSessionMessage_MessageType `protobuf_oneof:"message_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionMessage) Reset() {
	*x = SessionMessage{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMessage) ProtoMessage() {}

func (x *SessionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMessage.ProtoReflect.Descriptor instead.
func (*SessionMessage) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{12}
}

func (x *SessionMessage) GetMessageType() isSessionMessage_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *SessionMessage) GetJoinRequest() *JoinRequest {
	if x != nil {
		if x, ok := x.MessageType.(*SessionMessage_JoinRequest); ok {
			return x.JoinRequest
		}
	}
	return nil
}

func (x *SessionMessage) GetShareMessage() *ShareMessage {
	if x != nil {
		if x, ok := x.MessageType.(*SessionMessage_ShareMessage); ok {
			return x.ShareMessage
		}
	}
	return nil
}

func (x *SessionMessage) GetHeartbeatRequest() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.MessageType.(*SessionMessage_HeartbeatRequest); ok {
			return x.HeartbeatRequest
		}
	}
	return nil
}

func (x *SessionMessage) GetConfirmation() *SessionConfirmation {
	if x != nil {
		if x, ok := x.MessageType.(*SessionMessage_Confirmation); ok {
			return x.Confirmation
		}
	}
	return nil
}

func (x *SessionMessage) GetRoundMessage() *RoundMessage {
	if x != nil {
		if x, ok := x.MessageType.(*SessionMessage_RoundMessage); ok {
			return x.RoundMessage
		}
	}
	return nil
}

func (x *SessionMessage) GetCompletionMessage() *CompletionMessage {
	if x != nil {
		if x, ok := x.MessageType.(*SessionMessage_CompletionMessage); ok {
			return x.CompletionMessage
		}
	}
	return nil
}

func (x *SessionMessage) GetErrorMessage() *ErrorMessage {
	if x != nil {
		if x, ok := x.MessageType.(*SessionMessage_ErrorMessage); ok {
			return x.ErrorMessage
		}
	}
	return nil
}

type isSessionMessage_MessageType interface {
	isSessionMessage_MessageType()
}

type SessionMessage_JoinRequest struct {
	// 客户端 -> 服务端
	JoinRequest *JoinRequest `protobuf:"bytes,1,opt,name=join_request,json=joinRequest,proto3,oneof"`
}

type SessionMessage_ShareMessage struct {
	ShareMessage *ShareMessage `protobuf:"bytes,2,opt,name=share_message,json=shareMessage,proto3,oneof"`
}

type SessionMessage_HeartbeatRequest struct {
	HeartbeatRequest *HeartbeatRequest `protobuf:"bytes,3,opt,name=heartbeat_request,json=heartbeatRequest,proto3,oneof"`
}

type SessionMessage_Confirmation struct {
	// 服务端 -> 客户端
	Confirmation *SessionConfirmation `protobuf:"bytes,4,opt,name=confirmation,proto3,oneof"`
}

type SessionMessage_RoundMessage struct {
	RoundMessage *RoundMessage `protobuf:"bytes,5,opt,name=round_message,json=roundMessage,proto3,oneof"`
}

type SessionMessage_CompletionMessage struct {
	CompletionMessage *CompletionMessage `protobuf:"bytes,6,opt,name=completion_message,json=completionMessage,proto3,oneof"`
}

type SessionMessage_ErrorMessage struct {
	ErrorMessage *ErrorMessage `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3,oneof"`
}

func (*SessionMessage_JoinRequest) isSessionMessage_MessageType() {}

func (*SessionMessage_ShareMessage) isSessionMessage_MessageType() {}

func (*SessionMessage_HeartbeatRequest) isSessionMessage_MessageType() {}

func (*SessionMessage_Confirmation) isSessionMessage_MessageType() {}

func (*SessionMessage_RoundMessage) isSessionMessage_MessageType() {}

func (*SessionMessage_CompletionMessage) isSessionMessage_MessageType() {}

func (*SessionMessage_ErrorMessage) isSessionMessage_MessageType() {}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	JoinedAt      string                 `protobuf:"bytes,3,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{13}
}

func (x *JoinRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *JoinRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinRequest) GetJoinedAt() string {
	if x != nil {
		return x.JoinedAt
	}
	return ""
}

type ShareMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareData     []byte                 `protobuf:"bytes,1,opt,name=share_data,json=shareData,proto3" json:"share_data,omitempty"`
	Round         int32                  `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	SubmittedAt   string                 `protobuf:"bytes,3,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareMessage) Reset() {
	*x = ShareMessage{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareMessage) ProtoMessage() {}

func (x *ShareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareMessage.ProtoReflect.Descriptor instead.
func (*ShareMessage) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{14}
}

func (x *ShareMessage) GetShareData() []byte {
	if x != nil {
		return x.ShareData
	}
	return nil
}

func (x *ShareMessage) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *ShareMessage) GetSubmittedAt() string {
	if x != nil {
		return x.SubmittedAt
	}
	return ""
}

type SessionConfirmation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Threshold     int32                  `protobuf:"varint,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	TotalNodes    int32                  `protobuf:"varint,4,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	Participants  []string               `protobuf:"bytes,5,rep,name=participants,proto3" json:"participants,omitempty"`
	CurrentRound  int32                  `protobuf:"varint,6,opt,name=current_round,json=currentRound,proto3" json:"current_round,omitempty"`
	ConfirmedAt   string                 `protobuf:"bytes,7,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionConfirmation) Reset() {
	*x = SessionConfirmation{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionConfirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionConfirmation) ProtoMessage() {}

func (x *SessionConfirmation) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionConfirmation.ProtoReflect.Descriptor instead.
func (*SessionConfirmation) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{15}
}

func (x *SessionConfirmation) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionConfirmation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionConfirmation) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *SessionConfirmation) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *SessionConfirmation) GetParticipants() []string {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *SessionConfirmation) GetCurrentRound() int32 {
	if x != nil {
		return x.CurrentRound
	}
	return 0
}

func (x *SessionConfirmation) GetConfirmedAt() string {
	if x != nil {
		return x.ConfirmedAt
	}
	return ""
}

type RoundMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         int32                  `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	RoundType     string                 `protobuf:"bytes,2,opt,name=round_type,json=roundType,proto3" json:"round_type,omitempty"` // "dkg", "sign"
	MessageData   []byte                 `protobuf:"bytes,3,opt,name=message_data,json=messageData,proto3" json:"message_data,omitempty"`
	TargetNodes   []string               `protobuf:"bytes,4,rep,name=target_nodes,json=targetNodes,proto3" json:"target_nodes,omitempty"`
	SentAt        string                 `protobuf:"bytes,5,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundMessage) Reset() {
	*x = RoundMessage{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundMessage) ProtoMessage() {}

func (x *RoundMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundMessage.ProtoReflect.Descriptor instead.
func (*RoundMessage) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{16}
}

func (x *RoundMessage) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *RoundMessage) GetRoundType() string {
	if x != nil {
		return x.RoundType
	}
	return ""
}

func (x *RoundMessage) GetMessageData() []byte {
	if x != nil {
		return x.MessageData
	}
	return nil
}

func (x *RoundMessage) GetTargetNodes() []string {
	if x != nil {
		return x.TargetNodes
	}
	return nil
}

func (x *RoundMessage) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

type CompletionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	CompletedAt   string                 `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionMessage) Reset() {
	*x = CompletionMessage{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionMessage) ProtoMessage() {}

func (x *CompletionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionMessage.ProtoReflect.Descriptor instead.
func (*CompletionMessage) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{17}
}

func (x *CompletionMessage) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *CompletionMessage) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *CompletionMessage) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Recoverable   bool                   `protobuf:"varint,3,opt,name=recoverable,proto3" json:"recoverable,omitempty"`
	OccurredAt    string                 `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{18}
}

func (x *ErrorMessage) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ErrorMessage) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ErrorMessage) GetRecoverable() bool {
	if x != nil {
		return x.Recoverable
	}
	return false
}

func (x *ErrorMessage) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

// 心跳消息
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SentAt        string                 `protobuf:"bytes,2,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	StatusInfo    map[string]string      `protobuf:"bytes,3,rep,name=status_info,json=statusInfo,proto3" json:"status_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{19}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *HeartbeatRequest) GetStatusInfo() map[string]string {
	if x != nil {
		return x.StatusInfo
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	CoordinatorId string                 `protobuf:"bytes,2,opt,name=coordinator_id,json=coordinatorId,proto3" json:"coordinator_id,omitempty"`
	ReceivedAt    string                 `protobuf:"bytes,3,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	Instructions  map[string]string      `protobuf:"bytes,4,rep,name=instructions,proto3" json:"instructions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{20}
}

func (x *HeartbeatResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *HeartbeatResponse) GetCoordinatorId() string {
	if x != nil {
		return x.CoordinatorId
	}
	return ""
}

func (x *HeartbeatResponse) GetReceivedAt() string {
	if x != nil {
		return x.ReceivedAt
	}
	return ""
}

func (x *HeartbeatResponse) GetInstructions() map[string]string {
	if x != nil {
		return x.Instructions
	}
	return nil
}

var File_mpc_v1_mpc_proto protoreflect.FileDescriptor

const file_mpc_v1_mpc_proto_rawDesc = "" +
	"\n" +
	"\x10mpc/v1/mpc.proto\x12\x06mpc.v1\"\xb9\x01\n" +
	"\x14CreateSessionRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x12+\n" +
	"\x11participant_nodes\x18\x05 \x03(\tR\x10participantNodes\"\xfc\x01\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\x05R\tthreshold\x12\x1f\n" +
	"\vtotal_nodes\x18\x04 \x01(\x05R\n" +
	"totalNodes\x12/\n" +
	"\x13participating_nodes\x18\x05 \x03(\tR\x12participatingNodes\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\tR\texpiresAt\"5\n" +
	"\x14SessionStatusRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xc8\x02\n" +
	"\x15SessionStatusResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rcurrent_round\x18\x03 \x01(\x05R\fcurrentRound\x12!\n" +
	"\ftotal_rounds\x18\x04 \x01(\x05R\vtotalRounds\x12/\n" +
	"\x13participating_nodes\x18\x05 \x03(\tR\x12participatingNodes\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12!\n" +
	"\fcompleted_at\x18\b \x01(\tR\vcompletedAt\x12\x1f\n" +
	"\vduration_ms\x18\t \x01(\x05R\n" +
	"durationMs\"\x99\x01\n" +
	"\fShareRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"share_data\x18\x03 \x01(\fR\tshareData\x12\x14\n" +
	"\x05round\x18\x04 \x01(\x05R\x05round\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\"d\n" +
	"\rShareResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"next_round\x18\x03 \x01(\x05R\tnextRound\"\xd5\x01\n" +
	"\x0fStartDKGRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\x12\x14\n" +
	"\x05curve\x18\x04 \x01(\tR\x05curve\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x05R\tthreshold\x12\x1f\n" +
	"\vtotal_nodes\x18\x06 \x01(\x05R\n" +
	"totalNodes\x12\x19\n" +
	"\bnode_ids\x18\a \x03(\tR\anodeIds\"F\n" +
	"\x10StartDKGResponse\x12\x18\n" +
	"\astarted\x18\x01 \x01(\bR\astarted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf9\x01\n" +
	"\x10StartSignRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\fR\amessage\x12\x1f\n" +
	"\vmessage_hex\x18\x04 \x01(\tR\n" +
	"messageHex\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12\x1c\n" +
	"\tthreshold\x18\x06 \x01(\x05R\tthreshold\x12\x1f\n" +
	"\vtotal_nodes\x18\a \x01(\x05R\n" +
	"totalNodes\x12\x19\n" +
	"\bnode_ids\x18\b \x03(\tR\anodeIds\"G\n" +
	"\x11StartSignResponse\x12\x18\n" +
	"\astarted\x18\x01 \x01(\bR\astarted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"1\n" +
	"\x10AggregateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xb2\x01\n" +
	"\x11AggregateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12!\n" +
	"\fmessage_hash\x18\x04 \x01(\tR\vmessageHash\x12#\n" +
	"\raggregated_at\x18\x05 \x01(\tR\faggregatedAt\"\xe9\x03\n" +
	"\x0eSessionMessage\x128\n" +
	"\fjoin_request\x18\x01 \x01(\v2\x13.mpc.v1.JoinRequestH\x00R\vjoinRequest\x12;\n" +
	"\rshare_message\x18\x02 \x01(\v2\x14.mpc.v1.ShareMessageH\x00R\fshareMessage\x12G\n" +
	"\x11heartbeat_request\x18\x03 \x01(\v2\x18.mpc.v1.HeartbeatRequestH\x00R\x10heartbeatRequest\x12A\n" +
	"\fconfirmation\x18\x04 \x01(\v2\x1b.mpc.v1.SessionConfirmationH\x00R\fconfirmation\x12;\n" +
	"\rround_message\x18\x05 \x01(\v2\x14.mpc.v1.RoundMessageH\x00R\froundMessage\x12J\n" +
	"\x12completion_message\x18\x06 \x01(\v2\x19.mpc.v1.CompletionMessageH\x00R\x11completionMessage\x12;\n" +
	"\rerror_message\x18\a \x01(\v2\x14.mpc.v1.ErrorMessageH\x00R\ferrorMessageB\x0e\n" +
	"\fmessage_type\"b\n" +
	"\vJoinRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tjoined_at\x18\x03 \x01(\tR\bjoinedAt\"f\n" +
	"\fShareMessage\x12\x1d\n" +
	"\n" +
	"share_data\x18\x01 \x01(\fR\tshareData\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x05R\x05round\x12!\n" +
	"\fsubmitted_at\x18\x03 \x01(\tR\vsubmittedAt\"\xf7\x01\n" +
	"\x13SessionConfirmation\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\x05R\tthreshold\x12\x1f\n" +
	"\vtotal_nodes\x18\x04 \x01(\x05R\n" +
	"totalNodes\x12\"\n" +
	"\fparticipants\x18\x05 \x03(\tR\fparticipants\x12#\n" +
	"\rcurrent_round\x18\x06 \x01(\x05R\fcurrentRound\x12!\n" +
	"\fconfirmed_at\x18\a \x01(\tR\vconfirmedAt\"\xa2\x01\n" +
	"\fRoundMessage\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x05R\x05round\x12\x1d\n" +
	"\n" +
	"round_type\x18\x02 \x01(\tR\troundType\x12!\n" +
	"\fmessage_data\x18\x03 \x01(\fR\vmessageData\x12!\n" +
	"\ftarget_nodes\x18\x04 \x03(\tR\vtargetNodes\x12\x17\n" +
	"\asent_at\x18\x05 \x01(\tR\x06sentAt\"s\n" +
	"\x11CompletionMessage\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12!\n" +
	"\fcompleted_at\x18\x06 \x01(\tR\vcompletedAt\"\x95\x01\n" +
	"\fErrorMessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12 \n" +
	"\vrecoverable\x18\x03 \x01(\bR\vrecoverable\x12\x1f\n" +
	"\voccurred_at\x18\x04 \x01(\tR\n" +
	"occurredAt\"\xce\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\asent_at\x18\x02 \x01(\tR\x06sentAt\x12I\n" +
	"\vstatus_info\x18\x03 \x03(\v2(.mpc.v1.HeartbeatRequest.StatusInfoEntryR\n" +
	"statusInfo\x1a=\n" +
	"\x0fStatusInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x02\n" +
	"\x11HeartbeatResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\x12%\n" +
	"\x0ecoordinator_id\x18\x02 \x01(\tR\rcoordinatorId\x12\x1f\n" +
	"\vreceived_at\x18\x03 \x01(\tR\n" +
	"receivedAt\x12O\n" +
	"\finstructions\x18\x04 \x03(\v2+.mpc.v1.HeartbeatResponse.InstructionsEntryR\finstructions\x1a?\n" +
	"\x11InstructionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xdb\x02\n" +
	"\aMPCNode\x12H\n" +
	"\x12JoinSigningSession\x12\x16.mpc.v1.SessionMessage\x1a\x16.mpc.v1.SessionMessage(\x010\x01\x12=\n" +
	"\bStartDKG\x12\x17.mpc.v1.StartDKGRequest\x1a\x18.mpc.v1.StartDKGResponse\x12@\n" +
	"\tStartSign\x12\x18.mpc.v1.StartSignRequest\x1a\x19.mpc.v1.StartSignResponse\x12C\n" +
	"\x14SubmitSignatureShare\x12\x14.mpc.v1.ShareRequest\x1a\x15.mpc.v1.ShareResponse\x12@\n" +
	"\tHeartbeat\x12\x18.mpc.v1.HeartbeatRequest\x1a\x19.mpc.v1.HeartbeatResponse2\x82\x02\n" +
	"\x0eMPCCoordinator\x12S\n" +
	"\x14CreateSigningSession\x12\x1c.mpc.v1.CreateSessionRequest\x1a\x1d.mpc.v1.CreateSessionResponse\x12O\n" +
	"\x10GetSessionStatus\x12\x1c.mpc.v1.SessionStatusRequest\x1a\x1d.mpc.v1.SessionStatusResponse\x12J\n" +
	"\x13AggregateSignatures\x12\x18.mpc.v1.AggregateRequest\x1a\x19.mpc.v1.AggregateResponseB7Z5github.com/kashguard/go-mpc-wallet/internal/pb/mpc/v1b\x06proto3"

var (
	file_mpc_v1_mpc_proto_rawDescOnce sync.Once
	file_mpc_v1_mpc_proto_rawDescData []byte
)

func file_mpc_v1_mpc_proto_rawDescGZIP() []byte {
	file_mpc_v1_mpc_proto_rawDescOnce.Do(func() {
		file_mpc_v1_mpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mpc_v1_mpc_proto_rawDesc), len(file_mpc_v1_mpc_proto_rawDesc)))
	})
	return file_mpc_v1_mpc_proto_rawDescData
}

var file_mpc_v1_mpc_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_mpc_v1_mpc_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),  // 0: mpc.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil), // 1: mpc.v1.CreateSessionResponse
	(*SessionStatusRequest)(nil),  // 2: mpc.v1.SessionStatusRequest
	(*SessionStatusResponse)(nil), // 3: mpc.v1.SessionStatusResponse
	(*ShareRequest)(nil),          // 4: mpc.v1.ShareRequest
	(*ShareResponse)(nil),         // 5: mpc.v1.ShareResponse
	(*StartDKGRequest)(nil),       // 6: mpc.v1.StartDKGRequest
	(*StartDKGResponse)(nil),      // 7: mpc.v1.StartDKGResponse
	(*StartSignRequest)(nil),      // 8: mpc.v1.StartSignRequest
	(*StartSignResponse)(nil),     // 9: mpc.v1.StartSignResponse
	(*AggregateRequest)(nil),      // 10: mpc.v1.AggregateRequest
	(*AggregateResponse)(nil),     // 11: mpc.v1.AggregateResponse
	(*SessionMessage)(nil),        // 12: mpc.v1.SessionMessage
	(*JoinRequest)(nil),           // 13: mpc.v1.JoinRequest
	(*ShareMessage)(nil),          // 14: mpc.v1.ShareMessage
	(*SessionConfirmation)(nil),   // 15: mpc.v1.SessionConfirmation
	(*RoundMessage)(nil),          // 16: mpc.v1.RoundMessage
	(*CompletionMessage)(nil),     // 17: mpc.v1.CompletionMessage
	(*ErrorMessage)(nil),          // 18: mpc.v1.ErrorMessage
	(*HeartbeatRequest)(nil),      // 19: mpc.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 20: mpc.v1.HeartbeatResponse
	nil,                           // 21: mpc.v1.HeartbeatRequest.StatusInfoEntry
	nil,                           // 22: mpc.v1.HeartbeatResponse.InstructionsEntry
}
var file_mpc_v1_mpc_proto_depIdxs = []int32{
	13, // 0: mpc.v1.SessionMessage.join_request:type_name -> mpc.v1.JoinRequest
	14, // 1: mpc.v1.SessionMessage.share_message:type_name -> mpc.v1.ShareMessage
	19, // 2: mpc.v1.SessionMessage.heartbeat_request:type_name -> mpc.v1.HeartbeatRequest
	15, // 3: mpc.v1.SessionMessage.confirmation:type_name -> mpc.v1.SessionConfirmation
	16, // 4: mpc.v1.SessionMessage.round_message:type_name -> mpc.v1.RoundMessage
	17, // 5: mpc.v1.SessionMessage.completion_message:type_name -> mpc.v1.CompletionMessage
	18, // 6: mpc.v1.SessionMessage.error_message:type_name -> mpc.v1.ErrorMessage
	21, // 7: mpc.v1.HeartbeatRequest.status_info:type_name -> mpc.v1.HeartbeatRequest.StatusInfoEntry
	22, // 8: mpc.v1.HeartbeatResponse.instructions:type_name -> mpc.v1.HeartbeatResponse.InstructionsEntry
	12, // 9: mpc.v1.MPCNode.JoinSigningSession:input_type -> mpc.v1.SessionMessage
	6,  // 10: mpc.v1.MPCNode.StartDKG:input_type -> mpc.v1.StartDKGRequest
	8,  // 11: mpc.v1.MPCNode.StartSign:input_type -> mpc.v1.StartSignRequest
	4,  // 12: mpc.v1.MPCNode.SubmitSignatureShare:input_type -> mpc.v1.ShareRequest
	19, // 13: mpc.v1.MPCNode.Heartbeat:input_type -> mpc.v1.HeartbeatRequest
	0,  // 14: mpc.v1.MPCCoordinator.CreateSigningSession:input_type -> mpc.v1.CreateSessionRequest
	2,  // 15: mpc.v1.MPCCoordinator.GetSessionStatus:input_type -> mpc.v1.SessionStatusRequest
	10, // 16: mpc.v1.MPCCoordinator.AggregateSignatures:input_type -> mpc.v1.AggregateRequest
	12, // 17: mpc.v1.MPCNode.JoinSigningSession:output_type -> mpc.v1.SessionMessage
	7,  // 18: mpc.v1.MPCNode.StartDKG:output_type -> mpc.v1.StartDKGResponse
	9,  // 19: mpc.v1.MPCNode.StartSign:output_type -> mpc.v1.StartSignResponse
	5,  // 20: mpc.v1.MPCNode.SubmitSignatureShare:output_type -> mpc.v1.ShareResponse
	20, // 21: mpc.v1.MPCNode.Heartbeat:output_type -> mpc.v1.HeartbeatResponse
	1,  // 22: mpc.v1.MPCCoordinator.CreateSigningSession:output_type -> mpc.v1.CreateSessionResponse
	3,  // 23: mpc.v1.MPCCoordinator.GetSessionStatus:output_type -> mpc.v1.SessionStatusResponse
	11, // 24: mpc.v1.MPCCoordinator.AggregateSignatures:output_type -> mpc.v1.AggregateResponse
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_mpc_v1_mpc_proto_init() }
func file_mpc_v1_mpc_proto_init() {
	if File_mpc_v1_mpc_proto != nil {
		return
	}
	file_mpc_v1_mpc_proto_msgTypes[12].OneofWrappers = []any{
		(*SessionMessage_JoinRequest)(nil),
		(*SessionMessage_ShareMessage)(nil),
		(*SessionMessage_HeartbeatRequest)(nil),
		(*SessionMessage_Confirmation)(nil),
		(*SessionMessage_RoundMessage)(nil),
		(*SessionMessage_CompletionMessage)(nil),
		(*SessionMessage_ErrorMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mpc_v1_mpc_proto_rawDesc), len(file_mpc_v1_mpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_mpc_v1_mpc_proto_goTypes,
		DependencyIndexes: file_mpc_v1_mpc_proto_depIdxs,
		MessageInfos:      file_mpc_v1_mpc_proto_msgTypes,
	}.Build()
	File_mpc_v1_mpc_proto = out.File
	file_mpc_v1_mpc_proto_goTypes = nil
	file_mpc_v1_mpc_proto_depIdxs = nil
}
