// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AccessTokens        string
	AppUserProfiles     string
	AuditLogs           string
	ConfirmationTokens  string
	Keys                string
	Nodes               string
	PasswordResetTokens string
	PushTokens          string
	RefreshTokens       string
	SigningSessions     string
	Users               string
}{
	AccessTokens:        "access_tokens",
	AppUserProfiles:     "app_user_profiles",
	AuditLogs:           "audit_logs",
	ConfirmationTokens:  "confirmation_tokens",
	Keys:                "keys",
	Nodes:               "nodes",
	PasswordResetTokens: "password_reset_tokens",
	PushTokens:          "push_tokens",
	RefreshTokens:       "refresh_tokens",
	SigningSessions:     "signing_sessions",
	Users:               "users",
}
