// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Key is an object representing the database table.
type Key struct {
	KeyID        string      `boil:"key_id" json:"key_id" toml:"key_id" yaml:"key_id"`
	PublicKey    string      `boil:"public_key" json:"public_key" toml:"public_key" yaml:"public_key"`
	Algorithm    string      `boil:"algorithm" json:"algorithm" toml:"algorithm" yaml:"algorithm"`
	Curve        string      `boil:"curve" json:"curve" toml:"curve" yaml:"curve"`
	Threshold    int         `boil:"threshold" json:"threshold" toml:"threshold" yaml:"threshold"`
	TotalNodes   int         `boil:"total_nodes" json:"total_nodes" toml:"total_nodes" yaml:"total_nodes"`
	ChainType    string      `boil:"chain_type" json:"chain_type" toml:"chain_type" yaml:"chain_type"`
	Address      null.String `boil:"address" json:"address,omitempty" toml:"address" yaml:"address,omitempty"`
	Status       string      `boil:"status" json:"status" toml:"status" yaml:"status"`
	Description  null.String `boil:"description" json:"description,omitempty" toml:"description" yaml:"description,omitempty"`
	Tags         null.JSON   `boil:"tags" json:"tags,omitempty" toml:"tags" yaml:"tags,omitempty"`
	CreatedAt    time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt    time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	DeletionDate null.Time   `boil:"deletion_date" json:"deletion_date,omitempty" toml:"deletion_date" yaml:"deletion_date,omitempty"`

	R *keyR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L keyL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var KeyColumns = struct {
	KeyID        string
	PublicKey    string
	Algorithm    string
	Curve        string
	Threshold    string
	TotalNodes   string
	ChainType    string
	Address      string
	Status       string
	Description  string
	Tags         string
	CreatedAt    string
	UpdatedAt    string
	DeletionDate string
}{
	KeyID:        "key_id",
	PublicKey:    "public_key",
	Algorithm:    "algorithm",
	Curve:        "curve",
	Threshold:    "threshold",
	TotalNodes:   "total_nodes",
	ChainType:    "chain_type",
	Address:      "address",
	Status:       "status",
	Description:  "description",
	Tags:         "tags",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
	DeletionDate: "deletion_date",
}

var KeyTableColumns = struct {
	KeyID        string
	PublicKey    string
	Algorithm    string
	Curve        string
	Threshold    string
	TotalNodes   string
	ChainType    string
	Address      string
	Status       string
	Description  string
	Tags         string
	CreatedAt    string
	UpdatedAt    string
	DeletionDate string
}{
	KeyID:        "keys.key_id",
	PublicKey:    "keys.public_key",
	Algorithm:    "keys.algorithm",
	Curve:        "keys.curve",
	Threshold:    "keys.threshold",
	TotalNodes:   "keys.total_nodes",
	ChainType:    "keys.chain_type",
	Address:      "keys.address",
	Status:       "keys.status",
	Description:  "keys.description",
	Tags:         "keys.tags",
	CreatedAt:    "keys.created_at",
	UpdatedAt:    "keys.updated_at",
	DeletionDate: "keys.deletion_date",
}

// Generated where

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var KeyWhere = struct {
	KeyID        whereHelperstring
	PublicKey    whereHelperstring
	Algorithm    whereHelperstring
	Curve        whereHelperstring
	Threshold    whereHelperint
	TotalNodes   whereHelperint
	ChainType    whereHelperstring
	Address      whereHelpernull_String
	Status       whereHelperstring
	Description  whereHelpernull_String
	Tags         whereHelpernull_JSON
	CreatedAt    whereHelpertime_Time
	UpdatedAt    whereHelpertime_Time
	DeletionDate whereHelpernull_Time
}{
	KeyID:        whereHelperstring{field: "\"keys\".\"key_id\""},
	PublicKey:    whereHelperstring{field: "\"keys\".\"public_key\""},
	Algorithm:    whereHelperstring{field: "\"keys\".\"algorithm\""},
	Curve:        whereHelperstring{field: "\"keys\".\"curve\""},
	Threshold:    whereHelperint{field: "\"keys\".\"threshold\""},
	TotalNodes:   whereHelperint{field: "\"keys\".\"total_nodes\""},
	ChainType:    whereHelperstring{field: "\"keys\".\"chain_type\""},
	Address:      whereHelpernull_String{field: "\"keys\".\"address\""},
	Status:       whereHelperstring{field: "\"keys\".\"status\""},
	Description:  whereHelpernull_String{field: "\"keys\".\"description\""},
	Tags:         whereHelpernull_JSON{field: "\"keys\".\"tags\""},
	CreatedAt:    whereHelpertime_Time{field: "\"keys\".\"created_at\""},
	UpdatedAt:    whereHelpertime_Time{field: "\"keys\".\"updated_at\""},
	DeletionDate: whereHelpernull_Time{field: "\"keys\".\"deletion_date\""},
}

// KeyRels is where relationship names are stored.
var KeyRels = struct {
	SigningSessions string
}{
	SigningSessions: "SigningSessions",
}

// keyR is where relationships are stored.
type keyR struct {
	SigningSessions SigningSessionSlice `boil:"SigningSessions" json:"SigningSessions" toml:"SigningSessions" yaml:"SigningSessions"`
}

// NewStruct creates a new relationship struct
func (*keyR) NewStruct() *keyR {
	return &keyR{}
}

func (o *Key) GetSigningSessions() SigningSessionSlice {
	if o == nil {
		return nil
	}

	return o.R.GetSigningSessions()
}

func (r *keyR) GetSigningSessions() SigningSessionSlice {
	if r == nil {
		return nil
	}

	return r.SigningSessions
}

// keyL is where Load methods for each relationship are stored.
type keyL struct{}

var (
	keyAllColumns            = []string{"key_id", "public_key", "algorithm", "curve", "threshold", "total_nodes", "chain_type", "address", "status", "description", "tags", "created_at", "updated_at", "deletion_date"}
	keyColumnsWithoutDefault = []string{"key_id", "public_key", "algorithm", "curve", "threshold", "total_nodes", "chain_type", "status"}
	keyColumnsWithDefault    = []string{"address", "description", "tags", "created_at", "updated_at", "deletion_date"}
	keyPrimaryKeyColumns     = []string{"key_id"}
	keyGeneratedColumns      = []string{}
)

type (
	// KeySlice is an alias for a slice of pointers to Key.
	// This should almost always be used instead of []Key.
	KeySlice []*Key

	keyQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	keyType                 = reflect.TypeOf(&Key{})
	keyMapping              = queries.MakeStructMapping(keyType)
	keyPrimaryKeyMapping, _ = queries.BindMapping(keyType, keyMapping, keyPrimaryKeyColumns)
	keyInsertCacheMut       sync.RWMutex
	keyInsertCache          = make(map[string]insertCache)
	keyUpdateCacheMut       sync.RWMutex
	keyUpdateCache          = make(map[string]updateCache)
	keyUpsertCacheMut       sync.RWMutex
	keyUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single key record from the query.
func (q keyQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Key, error) {
	o := &Key{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for keys")
	}

	return o, nil
}

// All returns all Key records from the query.
func (q keyQuery) All(ctx context.Context, exec boil.ContextExecutor) (KeySlice, error) {
	var o []*Key

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Key slice")
	}

	return o, nil
}

// Count returns the count of all Key records in the query.
func (q keyQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count keys rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q keyQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if keys exists")
	}

	return count > 0, nil
}

// SigningSessions retrieves all the signing_session's SigningSessions with an executor.
func (o *Key) SigningSessions(mods ...qm.QueryMod) signingSessionQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"signing_sessions\".\"key_id\"=?", o.KeyID),
	)

	return SigningSessions(queryMods...)
}

// LoadSigningSessions allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (keyL) LoadSigningSessions(ctx context.Context, e boil.ContextExecutor, singular bool, maybeKey interface{}, mods queries.Applicator) error {
	var slice []*Key
	var object *Key

	if singular {
		var ok bool
		object, ok = maybeKey.(*Key)
		if !ok {
			object = new(Key)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeKey)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeKey))
			}
		}
	} else {
		s, ok := maybeKey.(*[]*Key)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeKey)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeKey))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &keyR{}
		}
		args[object.KeyID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &keyR{}
			}
			args[obj.KeyID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`signing_sessions`),
		qm.WhereIn(`signing_sessions.key_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load signing_sessions")
	}

	var resultSlice []*SigningSession
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice signing_sessions")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on signing_sessions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for signing_sessions")
	}

	if singular {
		object.R.SigningSessions = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &signingSessionR{}
			}
			foreign.R.Key = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.KeyID == foreign.KeyID {
				local.R.SigningSessions = append(local.R.SigningSessions, foreign)
				if foreign.R == nil {
					foreign.R = &signingSessionR{}
				}
				foreign.R.Key = local
				break
			}
		}
	}

	return nil
}

// AddSigningSessions adds the given related objects to the existing relationships
// of the key, optionally inserting them as new records.
// Appends related to o.R.SigningSessions.
// Sets related.R.Key appropriately.
func (o *Key) AddSigningSessions(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*SigningSession) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.KeyID = o.KeyID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"signing_sessions\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"key_id"}),
				strmangle.WhereClause("\"", "\"", 2, signingSessionPrimaryKeyColumns),
			)
			values := []interface{}{o.KeyID, rel.SessionID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.KeyID = o.KeyID
		}
	}

	if o.R == nil {
		o.R = &keyR{
			SigningSessions: related,
		}
	} else {
		o.R.SigningSessions = append(o.R.SigningSessions, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &signingSessionR{
				Key: o,
			}
		} else {
			rel.R.Key = o
		}
	}
	return nil
}

// Keys retrieves all the records using an executor.
func Keys(mods ...qm.QueryMod) keyQuery {
	mods = append(mods, qm.From("\"keys\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"keys\".*"})
	}

	return keyQuery{q}
}

// FindKey retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindKey(ctx context.Context, exec boil.ContextExecutor, keyID string, selectCols ...string) (*Key, error) {
	keyObj := &Key{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"keys\" where \"key_id\"=$1", sel,
	)

	q := queries.Raw(query, keyID)

	err := q.Bind(ctx, exec, keyObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from keys")
	}

	return keyObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Key) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no keys provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(keyColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	keyInsertCacheMut.RLock()
	cache, cached := keyInsertCache[key]
	keyInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			keyAllColumns,
			keyColumnsWithDefault,
			keyColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(keyType, keyMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(keyType, keyMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"keys\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"keys\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into keys")
	}

	if !cached {
		keyInsertCacheMut.Lock()
		keyInsertCache[key] = cache
		keyInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the Key.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Key) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	keyUpdateCacheMut.RLock()
	cache, cached := keyUpdateCache[key]
	keyUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			keyAllColumns,
			keyPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update keys, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"keys\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, keyPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(keyType, keyMapping, append(wl, keyPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update keys row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for keys")
	}

	if !cached {
		keyUpdateCacheMut.Lock()
		keyUpdateCache[key] = cache
		keyUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q keyQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for keys")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for keys")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o KeySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), keyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"keys\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, keyPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in key slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all key")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Key) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no keys provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(keyColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	keyUpsertCacheMut.RLock()
	cache, cached := keyUpsertCache[key]
	keyUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			keyAllColumns,
			keyColumnsWithDefault,
			keyColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			keyAllColumns,
			keyPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert keys, could not build update column list")
		}

		ret := strmangle.SetComplement(keyAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(keyPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert keys, could not build conflict column list")
			}

			conflict = make([]string, len(keyPrimaryKeyColumns))
			copy(conflict, keyPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"keys\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(keyType, keyMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(keyType, keyMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert keys")
	}

	if !cached {
		keyUpsertCacheMut.Lock()
		keyUpsertCache[key] = cache
		keyUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single Key record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Key) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Key provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), keyPrimaryKeyMapping)
	sql := "DELETE FROM \"keys\" WHERE \"key_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from keys")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for keys")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q keyQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no keyQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from keys")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for keys")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o KeySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), keyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"keys\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, keyPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from key slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for keys")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Key) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindKey(ctx, exec, o.KeyID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *KeySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := KeySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), keyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"keys\".* FROM \"keys\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, keyPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in KeySlice")
	}

	*o = slice

	return nil
}

// KeyExists checks if the Key row exists.
func KeyExists(ctx context.Context, exec boil.ContextExecutor, keyID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"keys\" where \"key_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, keyID)
	}
	row := exec.QueryRowContext(ctx, sql, keyID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if keys exists")
	}

	return exists, nil
}

// Exists checks if the Key row exists.
func (o *Key) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return KeyExists(ctx, exec, o.KeyID)
}
