// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testSigningSessions(t *testing.T) {
	t.Parallel()

	query := SigningSessions()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testSigningSessionsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningSession{}
	if err = randomize.Struct(seed, o, signingSessionDBTypes, true, signingSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SigningSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSigningSessionsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningSession{}
	if err = randomize.Struct(seed, o, signingSessionDBTypes, true, signingSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := SigningSessions().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SigningSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSigningSessionsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningSession{}
	if err = randomize.Struct(seed, o, signingSessionDBTypes, true, signingSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SigningSessionSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SigningSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSigningSessionsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningSession{}
	if err = randomize.Struct(seed, o, signingSessionDBTypes, true, signingSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := SigningSessionExists(ctx, tx, o.SessionID)
	if err != nil {
		t.Errorf("Unable to check if SigningSession exists: %s", err)
	}
	if !e {
		t.Errorf("Expected SigningSessionExists to return true, but got false.")
	}
}

func testSigningSessionsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningSession{}
	if err = randomize.Struct(seed, o, signingSessionDBTypes, true, signingSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	signingSessionFound, err := FindSigningSession(ctx, tx, o.SessionID)
	if err != nil {
		t.Error(err)
	}

	if signingSessionFound == nil {
		t.Error("want a record, got nil")
	}
}

func testSigningSessionsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningSession{}
	if err = randomize.Struct(seed, o, signingSessionDBTypes, true, signingSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = SigningSessions().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testSigningSessionsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningSession{}
	if err = randomize.Struct(seed, o, signingSessionDBTypes, true, signingSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := SigningSessions().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testSigningSessionsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	signingSessionOne := &SigningSession{}
	signingSessionTwo := &SigningSession{}
	if err = randomize.Struct(seed, signingSessionOne, signingSessionDBTypes, false, signingSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningSession struct: %s", err)
	}
	if err = randomize.Struct(seed, signingSessionTwo, signingSessionDBTypes, false, signingSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = signingSessionOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = signingSessionTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SigningSessions().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testSigningSessionsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	signingSessionOne := &SigningSession{}
	signingSessionTwo := &SigningSession{}
	if err = randomize.Struct(seed, signingSessionOne, signingSessionDBTypes, false, signingSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningSession struct: %s", err)
	}
	if err = randomize.Struct(seed, signingSessionTwo, signingSessionDBTypes, false, signingSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = signingSessionOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = signingSessionTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SigningSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testSigningSessionsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningSession{}
	if err = randomize.Struct(seed, o, signingSessionDBTypes, true, signingSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SigningSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSigningSessionsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningSession{}
	if err = randomize.Struct(seed, o, signingSessionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize SigningSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(signingSessionPrimaryKeyColumns, signingSessionColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := SigningSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSigningSessionToOneKeyUsingKey(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local SigningSession
	var foreign Key

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, signingSessionDBTypes, false, signingSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningSession struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, keyDBTypes, false, keyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Key struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.KeyID = foreign.KeyID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Key().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.KeyID != foreign.KeyID {
		t.Errorf("want: %v, got %v", foreign.KeyID, check.KeyID)
	}

	slice := SigningSessionSlice{&local}
	if err = local.L.LoadKey(ctx, tx, false, (*[]*SigningSession)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Key == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Key = nil
	if err = local.L.LoadKey(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Key == nil {
		t.Error("struct should have been eager loaded")
	}

}

func testSigningSessionToOneSetOpKeyUsingKey(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SigningSession
	var b, c Key

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, signingSessionDBTypes, false, strmangle.SetComplement(signingSessionPrimaryKeyColumns, signingSessionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, keyDBTypes, false, strmangle.SetComplement(keyPrimaryKeyColumns, keyColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, keyDBTypes, false, strmangle.SetComplement(keyPrimaryKeyColumns, keyColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Key{&b, &c} {
		err = a.SetKey(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Key != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.SigningSessions[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.KeyID != x.KeyID {
			t.Error("foreign key was wrong value", a.KeyID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.KeyID))
		reflect.Indirect(reflect.ValueOf(&a.KeyID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.KeyID != x.KeyID {
			t.Error("foreign key was wrong value", a.KeyID, x.KeyID)
		}
	}
}

func testSigningSessionsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningSession{}
	if err = randomize.Struct(seed, o, signingSessionDBTypes, true, signingSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSigningSessionsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningSession{}
	if err = randomize.Struct(seed, o, signingSessionDBTypes, true, signingSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SigningSessionSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSigningSessionsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningSession{}
	if err = randomize.Struct(seed, o, signingSessionDBTypes, true, signingSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SigningSessions().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	signingSessionDBTypes = map[string]string{`SessionID`: `character varying`, `KeyID`: `character varying`, `Protocol`: `character varying`, `Status`: `character varying`, `Threshold`: `integer`, `TotalNodes`: `integer`, `ParticipatingNodes`: `jsonb`, `CurrentRound`: `integer`, `TotalRounds`: `integer`, `Signature`: `text`, `CreatedAt`: `timestamp with time zone`, `CompletedAt`: `timestamp with time zone`, `DurationMS`: `integer`}
	_                     = bytes.MinRead
)

func testSigningSessionsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(signingSessionPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(signingSessionAllColumns) == len(signingSessionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SigningSession{}
	if err = randomize.Struct(seed, o, signingSessionDBTypes, true, signingSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SigningSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, signingSessionDBTypes, true, signingSessionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SigningSession struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testSigningSessionsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(signingSessionAllColumns) == len(signingSessionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SigningSession{}
	if err = randomize.Struct(seed, o, signingSessionDBTypes, true, signingSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SigningSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, signingSessionDBTypes, true, signingSessionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SigningSession struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(signingSessionAllColumns, signingSessionPrimaryKeyColumns) {
		fields = signingSessionAllColumns
	} else {
		fields = strmangle.SetComplement(
			signingSessionAllColumns,
			signingSessionPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := SigningSessionSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testSigningSessionsUpsert(t *testing.T) {
	t.Parallel()

	if len(signingSessionAllColumns) == len(signingSessionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := SigningSession{}
	if err = randomize.Struct(seed, &o, signingSessionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize SigningSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SigningSession: %s", err)
	}

	count, err := SigningSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, signingSessionDBTypes, false, signingSessionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SigningSession struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SigningSession: %s", err)
	}

	count, err = SigningSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
