// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// SigningSession is an object representing the database table.
type SigningSession struct {
	SessionID          string      `boil:"session_id" json:"session_id" toml:"session_id" yaml:"session_id"`
	KeyID              string      `boil:"key_id" json:"key_id" toml:"key_id" yaml:"key_id"`
	Protocol           string      `boil:"protocol" json:"protocol" toml:"protocol" yaml:"protocol"`
	Status             string      `boil:"status" json:"status" toml:"status" yaml:"status"`
	Threshold          int         `boil:"threshold" json:"threshold" toml:"threshold" yaml:"threshold"`
	TotalNodes         int         `boil:"total_nodes" json:"total_nodes" toml:"total_nodes" yaml:"total_nodes"`
	ParticipatingNodes null.JSON   `boil:"participating_nodes" json:"participating_nodes,omitempty" toml:"participating_nodes" yaml:"participating_nodes,omitempty"`
	CurrentRound       null.Int    `boil:"current_round" json:"current_round,omitempty" toml:"current_round" yaml:"current_round,omitempty"`
	TotalRounds        int         `boil:"total_rounds" json:"total_rounds" toml:"total_rounds" yaml:"total_rounds"`
	Signature          null.String `boil:"signature" json:"signature,omitempty" toml:"signature" yaml:"signature,omitempty"`
	CreatedAt          time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	CompletedAt        null.Time   `boil:"completed_at" json:"completed_at,omitempty" toml:"completed_at" yaml:"completed_at,omitempty"`
	DurationMS         null.Int    `boil:"duration_ms" json:"duration_ms,omitempty" toml:"duration_ms" yaml:"duration_ms,omitempty"`

	R *signingSessionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L signingSessionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SigningSessionColumns = struct {
	SessionID          string
	KeyID              string
	Protocol           string
	Status             string
	Threshold          string
	TotalNodes         string
	ParticipatingNodes string
	CurrentRound       string
	TotalRounds        string
	Signature          string
	CreatedAt          string
	CompletedAt        string
	DurationMS         string
}{
	SessionID:          "session_id",
	KeyID:              "key_id",
	Protocol:           "protocol",
	Status:             "status",
	Threshold:          "threshold",
	TotalNodes:         "total_nodes",
	ParticipatingNodes: "participating_nodes",
	CurrentRound:       "current_round",
	TotalRounds:        "total_rounds",
	Signature:          "signature",
	CreatedAt:          "created_at",
	CompletedAt:        "completed_at",
	DurationMS:         "duration_ms",
}

var SigningSessionTableColumns = struct {
	SessionID          string
	KeyID              string
	Protocol           string
	Status             string
	Threshold          string
	TotalNodes         string
	ParticipatingNodes string
	CurrentRound       string
	TotalRounds        string
	Signature          string
	CreatedAt          string
	CompletedAt        string
	DurationMS         string
}{
	SessionID:          "signing_sessions.session_id",
	KeyID:              "signing_sessions.key_id",
	Protocol:           "signing_sessions.protocol",
	Status:             "signing_sessions.status",
	Threshold:          "signing_sessions.threshold",
	TotalNodes:         "signing_sessions.total_nodes",
	ParticipatingNodes: "signing_sessions.participating_nodes",
	CurrentRound:       "signing_sessions.current_round",
	TotalRounds:        "signing_sessions.total_rounds",
	Signature:          "signing_sessions.signature",
	CreatedAt:          "signing_sessions.created_at",
	CompletedAt:        "signing_sessions.completed_at",
	DurationMS:         "signing_sessions.duration_ms",
}

// Generated where

type whereHelpernull_Int struct{ field string }

func (w whereHelpernull_Int) EQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int) NEQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int) LT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int) LTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int) GT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int) GTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Int) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Int) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Int) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var SigningSessionWhere = struct {
	SessionID          whereHelperstring
	KeyID              whereHelperstring
	Protocol           whereHelperstring
	Status             whereHelperstring
	Threshold          whereHelperint
	TotalNodes         whereHelperint
	ParticipatingNodes whereHelpernull_JSON
	CurrentRound       whereHelpernull_Int
	TotalRounds        whereHelperint
	Signature          whereHelpernull_String
	CreatedAt          whereHelpertime_Time
	CompletedAt        whereHelpernull_Time
	DurationMS         whereHelpernull_Int
}{
	SessionID:          whereHelperstring{field: "\"signing_sessions\".\"session_id\""},
	KeyID:              whereHelperstring{field: "\"signing_sessions\".\"key_id\""},
	Protocol:           whereHelperstring{field: "\"signing_sessions\".\"protocol\""},
	Status:             whereHelperstring{field: "\"signing_sessions\".\"status\""},
	Threshold:          whereHelperint{field: "\"signing_sessions\".\"threshold\""},
	TotalNodes:         whereHelperint{field: "\"signing_sessions\".\"total_nodes\""},
	ParticipatingNodes: whereHelpernull_JSON{field: "\"signing_sessions\".\"participating_nodes\""},
	CurrentRound:       whereHelpernull_Int{field: "\"signing_sessions\".\"current_round\""},
	TotalRounds:        whereHelperint{field: "\"signing_sessions\".\"total_rounds\""},
	Signature:          whereHelpernull_String{field: "\"signing_sessions\".\"signature\""},
	CreatedAt:          whereHelpertime_Time{field: "\"signing_sessions\".\"created_at\""},
	CompletedAt:        whereHelpernull_Time{field: "\"signing_sessions\".\"completed_at\""},
	DurationMS:         whereHelpernull_Int{field: "\"signing_sessions\".\"duration_ms\""},
}

// SigningSessionRels is where relationship names are stored.
var SigningSessionRels = struct {
	Key string
}{
	Key: "Key",
}

// signingSessionR is where relationships are stored.
type signingSessionR struct {
	Key *Key `boil:"Key" json:"Key" toml:"Key" yaml:"Key"`
}

// NewStruct creates a new relationship struct
func (*signingSessionR) NewStruct() *signingSessionR {
	return &signingSessionR{}
}

func (o *SigningSession) GetKey() *Key {
	if o == nil {
		return nil
	}

	return o.R.GetKey()
}

func (r *signingSessionR) GetKey() *Key {
	if r == nil {
		return nil
	}

	return r.Key
}

// signingSessionL is where Load methods for each relationship are stored.
type signingSessionL struct{}

var (
	signingSessionAllColumns            = []string{"session_id", "key_id", "protocol", "status", "threshold", "total_nodes", "participating_nodes", "current_round", "total_rounds", "signature", "created_at", "completed_at", "duration_ms"}
	signingSessionColumnsWithoutDefault = []string{"session_id", "key_id", "protocol", "status", "threshold", "total_nodes", "total_rounds"}
	signingSessionColumnsWithDefault    = []string{"participating_nodes", "current_round", "signature", "created_at", "completed_at", "duration_ms"}
	signingSessionPrimaryKeyColumns     = []string{"session_id"}
	signingSessionGeneratedColumns      = []string{}
)

type (
	// SigningSessionSlice is an alias for a slice of pointers to SigningSession.
	// This should almost always be used instead of []SigningSession.
	SigningSessionSlice []*SigningSession

	signingSessionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	signingSessionType                 = reflect.TypeOf(&SigningSession{})
	signingSessionMapping              = queries.MakeStructMapping(signingSessionType)
	signingSessionPrimaryKeyMapping, _ = queries.BindMapping(signingSessionType, signingSessionMapping, signingSessionPrimaryKeyColumns)
	signingSessionInsertCacheMut       sync.RWMutex
	signingSessionInsertCache          = make(map[string]insertCache)
	signingSessionUpdateCacheMut       sync.RWMutex
	signingSessionUpdateCache          = make(map[string]updateCache)
	signingSessionUpsertCacheMut       sync.RWMutex
	signingSessionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single signingSession record from the query.
func (q signingSessionQuery) One(ctx context.Context, exec boil.ContextExecutor) (*SigningSession, error) {
	o := &SigningSession{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for signing_sessions")
	}

	return o, nil
}

// All returns all SigningSession records from the query.
func (q signingSessionQuery) All(ctx context.Context, exec boil.ContextExecutor) (SigningSessionSlice, error) {
	var o []*SigningSession

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to SigningSession slice")
	}

	return o, nil
}

// Count returns the count of all SigningSession records in the query.
func (q signingSessionQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count signing_sessions rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q signingSessionQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if signing_sessions exists")
	}

	return count > 0, nil
}

// Key pointed to by the foreign key.
func (o *SigningSession) Key(mods ...qm.QueryMod) keyQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"key_id\" = ?", o.KeyID),
	}

	queryMods = append(queryMods, mods...)

	return Keys(queryMods...)
}

// LoadKey allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (signingSessionL) LoadKey(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSigningSession interface{}, mods queries.Applicator) error {
	var slice []*SigningSession
	var object *SigningSession

	if singular {
		var ok bool
		object, ok = maybeSigningSession.(*SigningSession)
		if !ok {
			object = new(SigningSession)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSigningSession)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSigningSession))
			}
		}
	} else {
		s, ok := maybeSigningSession.(*[]*SigningSession)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSigningSession)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSigningSession))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &signingSessionR{}
		}
		args[object.KeyID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &signingSessionR{}
			}

			args[obj.KeyID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`keys`),
		qm.WhereIn(`keys.key_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Key")
	}

	var resultSlice []*Key
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Key")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for keys")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for keys")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Key = foreign
		if foreign.R == nil {
			foreign.R = &keyR{}
		}
		foreign.R.SigningSessions = append(foreign.R.SigningSessions, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.KeyID == foreign.KeyID {
				local.R.Key = foreign
				if foreign.R == nil {
					foreign.R = &keyR{}
				}
				foreign.R.SigningSessions = append(foreign.R.SigningSessions, local)
				break
			}
		}
	}

	return nil
}

// SetKey of the signingSession to the related item.
// Sets o.R.Key to related.
// Adds o to related.R.SigningSessions.
func (o *SigningSession) SetKey(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Key) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"signing_sessions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"key_id"}),
		strmangle.WhereClause("\"", "\"", 2, signingSessionPrimaryKeyColumns),
	)
	values := []interface{}{related.KeyID, o.SessionID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.KeyID = related.KeyID
	if o.R == nil {
		o.R = &signingSessionR{
			Key: related,
		}
	} else {
		o.R.Key = related
	}

	if related.R == nil {
		related.R = &keyR{
			SigningSessions: SigningSessionSlice{o},
		}
	} else {
		related.R.SigningSessions = append(related.R.SigningSessions, o)
	}

	return nil
}

// SigningSessions retrieves all the records using an executor.
func SigningSessions(mods ...qm.QueryMod) signingSessionQuery {
	mods = append(mods, qm.From("\"signing_sessions\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"signing_sessions\".*"})
	}

	return signingSessionQuery{q}
}

// FindSigningSession retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSigningSession(ctx context.Context, exec boil.ContextExecutor, sessionID string, selectCols ...string) (*SigningSession, error) {
	signingSessionObj := &SigningSession{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"signing_sessions\" where \"session_id\"=$1", sel,
	)

	q := queries.Raw(query, sessionID)

	err := q.Bind(ctx, exec, signingSessionObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from signing_sessions")
	}

	return signingSessionObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *SigningSession) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no signing_sessions provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(signingSessionColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	signingSessionInsertCacheMut.RLock()
	cache, cached := signingSessionInsertCache[key]
	signingSessionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			signingSessionAllColumns,
			signingSessionColumnsWithDefault,
			signingSessionColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(signingSessionType, signingSessionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(signingSessionType, signingSessionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"signing_sessions\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"signing_sessions\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into signing_sessions")
	}

	if !cached {
		signingSessionInsertCacheMut.Lock()
		signingSessionInsertCache[key] = cache
		signingSessionInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the SigningSession.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *SigningSession) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	signingSessionUpdateCacheMut.RLock()
	cache, cached := signingSessionUpdateCache[key]
	signingSessionUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			signingSessionAllColumns,
			signingSessionPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update signing_sessions, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"signing_sessions\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, signingSessionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(signingSessionType, signingSessionMapping, append(wl, signingSessionPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update signing_sessions row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for signing_sessions")
	}

	if !cached {
		signingSessionUpdateCacheMut.Lock()
		signingSessionUpdateCache[key] = cache
		signingSessionUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q signingSessionQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for signing_sessions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for signing_sessions")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SigningSessionSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), signingSessionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"signing_sessions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, signingSessionPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in signingSession slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all signingSession")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *SigningSession) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no signing_sessions provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(signingSessionColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	signingSessionUpsertCacheMut.RLock()
	cache, cached := signingSessionUpsertCache[key]
	signingSessionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			signingSessionAllColumns,
			signingSessionColumnsWithDefault,
			signingSessionColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			signingSessionAllColumns,
			signingSessionPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert signing_sessions, could not build update column list")
		}

		ret := strmangle.SetComplement(signingSessionAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(signingSessionPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert signing_sessions, could not build conflict column list")
			}

			conflict = make([]string, len(signingSessionPrimaryKeyColumns))
			copy(conflict, signingSessionPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"signing_sessions\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(signingSessionType, signingSessionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(signingSessionType, signingSessionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert signing_sessions")
	}

	if !cached {
		signingSessionUpsertCacheMut.Lock()
		signingSessionUpsertCache[key] = cache
		signingSessionUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single SigningSession record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *SigningSession) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no SigningSession provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), signingSessionPrimaryKeyMapping)
	sql := "DELETE FROM \"signing_sessions\" WHERE \"session_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from signing_sessions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for signing_sessions")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q signingSessionQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no signingSessionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from signing_sessions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for signing_sessions")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SigningSessionSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), signingSessionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"signing_sessions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, signingSessionPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from signingSession slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for signing_sessions")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *SigningSession) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSigningSession(ctx, exec, o.SessionID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SigningSessionSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SigningSessionSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), signingSessionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"signing_sessions\".* FROM \"signing_sessions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, signingSessionPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in SigningSessionSlice")
	}

	*o = slice

	return nil
}

// SigningSessionExists checks if the SigningSession row exists.
func SigningSessionExists(ctx context.Context, exec boil.ContextExecutor, sessionID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"signing_sessions\" where \"session_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, sessionID)
	}
	row := exec.QueryRowContext(ctx, sql, sessionID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if signing_sessions exists")
	}

	return exists, nil
}

// Exists checks if the SigningSession row exists.
func (o *SigningSession) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return SigningSessionExists(ctx, exec, o.SessionID)
}
