// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.4
// source: backup.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BackupService_RecoverMPCShare_FullMethodName  = "/infrastructure.v1.BackupService/RecoverMPCShare"
	BackupService_GetBackupStatus_FullMethodName  = "/infrastructure.v1.BackupService/GetBackupStatus"
	BackupService_ListBackupShares_FullMethodName = "/infrastructure.v1.BackupService/ListBackupShares"
)

// BackupServiceClient is the client API for BackupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BackupService 备份服务
type BackupServiceClient interface {
	// 恢复MPC分片（从SSS备份分片）
	RecoverMPCShare(ctx context.Context, in *RecoverMPCShareRequest, opts ...grpc.CallOption) (*RecoverMPCShareResponse, error)
	// 获取备份状态
	GetBackupStatus(ctx context.Context, in *GetBackupStatusRequest, opts ...grpc.CallOption) (*GetBackupStatusResponse, error)
	// 列出备份分片
	ListBackupShares(ctx context.Context, in *ListBackupSharesRequest, opts ...grpc.CallOption) (*ListBackupSharesResponse, error)
}

type backupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBackupServiceClient(cc grpc.ClientConnInterface) BackupServiceClient {
	return &backupServiceClient{cc}
}

func (c *backupServiceClient) RecoverMPCShare(ctx context.Context, in *RecoverMPCShareRequest, opts ...grpc.CallOption) (*RecoverMPCShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecoverMPCShareResponse)
	err := c.cc.Invoke(ctx, BackupService_RecoverMPCShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) GetBackupStatus(ctx context.Context, in *GetBackupStatusRequest, opts ...grpc.CallOption) (*GetBackupStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBackupStatusResponse)
	err := c.cc.Invoke(ctx, BackupService_GetBackupStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) ListBackupShares(ctx context.Context, in *ListBackupSharesRequest, opts ...grpc.CallOption) (*ListBackupSharesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBackupSharesResponse)
	err := c.cc.Invoke(ctx, BackupService_ListBackupShares_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackupServiceServer is the server API for BackupService service.
// All implementations must embed UnimplementedBackupServiceServer
// for forward compatibility.
//
// BackupService 备份服务
type BackupServiceServer interface {
	// 恢复MPC分片（从SSS备份分片）
	RecoverMPCShare(context.Context, *RecoverMPCShareRequest) (*RecoverMPCShareResponse, error)
	// 获取备份状态
	GetBackupStatus(context.Context, *GetBackupStatusRequest) (*GetBackupStatusResponse, error)
	// 列出备份分片
	ListBackupShares(context.Context, *ListBackupSharesRequest) (*ListBackupSharesResponse, error)
	mustEmbedUnimplementedBackupServiceServer()
}

// UnimplementedBackupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackupServiceServer struct{}

func (UnimplementedBackupServiceServer) RecoverMPCShare(context.Context, *RecoverMPCShareRequest) (*RecoverMPCShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecoverMPCShare not implemented")
}
func (UnimplementedBackupServiceServer) GetBackupStatus(context.Context, *GetBackupStatusRequest) (*GetBackupStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBackupStatus not implemented")
}
func (UnimplementedBackupServiceServer) ListBackupShares(context.Context, *ListBackupSharesRequest) (*ListBackupSharesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBackupShares not implemented")
}
func (UnimplementedBackupServiceServer) mustEmbedUnimplementedBackupServiceServer() {}
func (UnimplementedBackupServiceServer) testEmbeddedByValue()                       {}

// UnsafeBackupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackupServiceServer will
// result in compilation errors.
type UnsafeBackupServiceServer interface {
	mustEmbedUnimplementedBackupServiceServer()
}

func RegisterBackupServiceServer(s grpc.ServiceRegistrar, srv BackupServiceServer) {
	// If the following call panics, it indicates UnimplementedBackupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BackupService_ServiceDesc, srv)
}

func _BackupService_RecoverMPCShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverMPCShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).RecoverMPCShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_RecoverMPCShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).RecoverMPCShare(ctx, req.(*RecoverMPCShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_GetBackupStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBackupStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).GetBackupStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_GetBackupStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).GetBackupStatus(ctx, req.(*GetBackupStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_ListBackupShares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBackupSharesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).ListBackupShares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_ListBackupShares_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).ListBackupShares(ctx, req.(*ListBackupSharesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackupService_ServiceDesc is the grpc.ServiceDesc for BackupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infrastructure.v1.BackupService",
	HandlerType: (*BackupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecoverMPCShare",
			Handler:    _BackupService_RecoverMPCShare_Handler,
		},
		{
			MethodName: "GetBackupStatus",
			Handler:    _BackupService_GetBackupStatus_Handler,
		},
		{
			MethodName: "ListBackupShares",
			Handler:    _BackupService_ListBackupShares_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backup.proto",
}
