// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: key.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateRootKeyRequest 创建根密钥请求
type CreateRootKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`                 // 可选的密钥ID，如果为空则自动生成
	Algorithm     string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`                      // ECDSA, EdDSA, Schnorr
	Curve         string                 `protobuf:"bytes,3,opt,name=curve,proto3" json:"curve,omitempty"`                              // secp256k1, secp256r1, ed25519
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`                        // gg18, gg20, frost
	Threshold     int32                  `protobuf:"varint,5,opt,name=threshold,proto3" json:"threshold,omitempty"`                     // 默认 2
	TotalNodes    int32                  `protobuf:"varint,6,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"` // 默认 3
	UserId        string                 `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`              // 用户ID，用于生成客户端节点ID
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRootKeyRequest) Reset() {
	*x = CreateRootKeyRequest{}
	mi := &file_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRootKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRootKeyRequest) ProtoMessage() {}

func (x *CreateRootKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRootKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateRootKeyRequest) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRootKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *CreateRootKeyRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *CreateRootKeyRequest) GetCurve() string {
	if x != nil {
		return x.Curve
	}
	return ""
}

func (x *CreateRootKeyRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *CreateRootKeyRequest) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *CreateRootKeyRequest) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *CreateRootKeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateRootKeyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRootKeyRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// CreateRootKeyResponse 创建根密钥响应
type CreateRootKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *RootKeyMetadata       `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRootKeyResponse) Reset() {
	*x = CreateRootKeyResponse{}
	mi := &file_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRootKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRootKeyResponse) ProtoMessage() {}

func (x *CreateRootKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRootKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateRootKeyResponse) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRootKeyResponse) GetKey() *RootKeyMetadata {
	if x != nil {
		return x.Key
	}
	return nil
}

// GetRootKeyRequest 获取根密钥请求
type GetRootKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRootKeyRequest) Reset() {
	*x = GetRootKeyRequest{}
	mi := &file_key_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRootKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRootKeyRequest) ProtoMessage() {}

func (x *GetRootKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRootKeyRequest.ProtoReflect.Descriptor instead.
func (*GetRootKeyRequest) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{2}
}

func (x *GetRootKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

// GetRootKeyResponse 获取根密钥响应
type GetRootKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *RootKeyMetadata       `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRootKeyResponse) Reset() {
	*x = GetRootKeyResponse{}
	mi := &file_key_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRootKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRootKeyResponse) ProtoMessage() {}

func (x *GetRootKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRootKeyResponse.ProtoReflect.Descriptor instead.
func (*GetRootKeyResponse) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{3}
}

func (x *GetRootKeyResponse) GetKey() *RootKeyMetadata {
	if x != nil {
		return x.Key
	}
	return nil
}

// DeleteRootKeyRequest 删除根密钥请求
type DeleteRootKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRootKeyRequest) Reset() {
	*x = DeleteRootKeyRequest{}
	mi := &file_key_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRootKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRootKeyRequest) ProtoMessage() {}

func (x *DeleteRootKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRootKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteRootKeyRequest) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRootKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

// ListRootKeysRequest 列出根密钥请求
type ListRootKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // Active, Inactive, Deleted
	Pagination    *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRootKeysRequest) Reset() {
	*x = ListRootKeysRequest{}
	mi := &file_key_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRootKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRootKeysRequest) ProtoMessage() {}

func (x *ListRootKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRootKeysRequest.ProtoReflect.Descriptor instead.
func (*ListRootKeysRequest) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{5}
}

func (x *ListRootKeysRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListRootKeysRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// ListRootKeysResponse 列出根密钥响应
type ListRootKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*RootKeyMetadata     `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRootKeysResponse) Reset() {
	*x = ListRootKeysResponse{}
	mi := &file_key_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRootKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRootKeysResponse) ProtoMessage() {}

func (x *ListRootKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRootKeysResponse.ProtoReflect.Descriptor instead.
func (*ListRootKeysResponse) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{6}
}

func (x *ListRootKeysResponse) GetKeys() []*RootKeyMetadata {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *ListRootKeysResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// DeriveWalletKeyRequest 派生钱包密钥请求
type DeriveWalletKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootKeyId     string                 `protobuf:"bytes,1,opt,name=root_key_id,json=rootKeyId,proto3" json:"root_key_id,omitempty"`
	ChainType     string                 `protobuf:"bytes,2,opt,name=chain_type,json=chainType,proto3" json:"chain_type,omitempty"` // bitcoin, ethereum, solana
	Index         uint32                 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeriveWalletKeyRequest) Reset() {
	*x = DeriveWalletKeyRequest{}
	mi := &file_key_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeriveWalletKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeriveWalletKeyRequest) ProtoMessage() {}

func (x *DeriveWalletKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeriveWalletKeyRequest.ProtoReflect.Descriptor instead.
func (*DeriveWalletKeyRequest) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{7}
}

func (x *DeriveWalletKeyRequest) GetRootKeyId() string {
	if x != nil {
		return x.RootKeyId
	}
	return ""
}

func (x *DeriveWalletKeyRequest) GetChainType() string {
	if x != nil {
		return x.ChainType
	}
	return ""
}

func (x *DeriveWalletKeyRequest) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DeriveWalletKeyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DeriveWalletKeyRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// DeriveWalletKeyResponse 派生钱包密钥响应
type DeriveWalletKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *WalletKeyMetadata     `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeriveWalletKeyResponse) Reset() {
	*x = DeriveWalletKeyResponse{}
	mi := &file_key_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeriveWalletKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeriveWalletKeyResponse) ProtoMessage() {}

func (x *DeriveWalletKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeriveWalletKeyResponse.ProtoReflect.Descriptor instead.
func (*DeriveWalletKeyResponse) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{8}
}

func (x *DeriveWalletKeyResponse) GetWallet() *WalletKeyMetadata {
	if x != nil {
		return x.Wallet
	}
	return nil
}

// GetWalletKeyRequest 获取钱包密钥请求
type GetWalletKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletKeyRequest) Reset() {
	*x = GetWalletKeyRequest{}
	mi := &file_key_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletKeyRequest) ProtoMessage() {}

func (x *GetWalletKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletKeyRequest.ProtoReflect.Descriptor instead.
func (*GetWalletKeyRequest) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{9}
}

func (x *GetWalletKeyRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

// GetWalletKeyResponse 获取钱包密钥响应
type GetWalletKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *WalletKeyMetadata     `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletKeyResponse) Reset() {
	*x = GetWalletKeyResponse{}
	mi := &file_key_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletKeyResponse) ProtoMessage() {}

func (x *GetWalletKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletKeyResponse.ProtoReflect.Descriptor instead.
func (*GetWalletKeyResponse) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{10}
}

func (x *GetWalletKeyResponse) GetWallet() *WalletKeyMetadata {
	if x != nil {
		return x.Wallet
	}
	return nil
}

// ListWalletKeysRequest 列出钱包密钥请求
type ListWalletKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootKeyId     string                 `protobuf:"bytes,1,opt,name=root_key_id,json=rootKeyId,proto3" json:"root_key_id,omitempty"`
	ChainType     string                 `protobuf:"bytes,2,opt,name=chain_type,json=chainType,proto3" json:"chain_type,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWalletKeysRequest) Reset() {
	*x = ListWalletKeysRequest{}
	mi := &file_key_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWalletKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWalletKeysRequest) ProtoMessage() {}

func (x *ListWalletKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWalletKeysRequest.ProtoReflect.Descriptor instead.
func (*ListWalletKeysRequest) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{11}
}

func (x *ListWalletKeysRequest) GetRootKeyId() string {
	if x != nil {
		return x.RootKeyId
	}
	return ""
}

func (x *ListWalletKeysRequest) GetChainType() string {
	if x != nil {
		return x.ChainType
	}
	return ""
}

func (x *ListWalletKeysRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// ListWalletKeysResponse 列出钱包密钥响应
type ListWalletKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallets       []*WalletKeyMetadata   `protobuf:"bytes,1,rep,name=wallets,proto3" json:"wallets,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWalletKeysResponse) Reset() {
	*x = ListWalletKeysResponse{}
	mi := &file_key_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWalletKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWalletKeysResponse) ProtoMessage() {}

func (x *ListWalletKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWalletKeysResponse.ProtoReflect.Descriptor instead.
func (*ListWalletKeysResponse) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{12}
}

func (x *ListWalletKeysResponse) GetWallets() []*WalletKeyMetadata {
	if x != nil {
		return x.Wallets
	}
	return nil
}

func (x *ListWalletKeysResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// RootKeyMetadata 根密钥元数据
type RootKeyMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Algorithm     string                 `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Curve         string                 `protobuf:"bytes,4,opt,name=curve,proto3" json:"curve,omitempty"`
	Threshold     int32                  `protobuf:"varint,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	TotalNodes    int32                  `protobuf:"varint,6,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	Protocol      string                 `protobuf:"bytes,7,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletionDate  string                 `protobuf:"bytes,13,opt,name=deletion_date,json=deletionDate,proto3" json:"deletion_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootKeyMetadata) Reset() {
	*x = RootKeyMetadata{}
	mi := &file_key_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootKeyMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootKeyMetadata) ProtoMessage() {}

func (x *RootKeyMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootKeyMetadata.ProtoReflect.Descriptor instead.
func (*RootKeyMetadata) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{13}
}

func (x *RootKeyMetadata) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *RootKeyMetadata) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *RootKeyMetadata) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *RootKeyMetadata) GetCurve() string {
	if x != nil {
		return x.Curve
	}
	return ""
}

func (x *RootKeyMetadata) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *RootKeyMetadata) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *RootKeyMetadata) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *RootKeyMetadata) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RootKeyMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RootKeyMetadata) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RootKeyMetadata) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RootKeyMetadata) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *RootKeyMetadata) GetDeletionDate() string {
	if x != nil {
		return x.DeletionDate
	}
	return ""
}

// WalletKeyMetadata 钱包密钥元数据
type WalletKeyMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	RootKeyId     string                 `protobuf:"bytes,2,opt,name=root_key_id,json=rootKeyId,proto3" json:"root_key_id,omitempty"`
	ChainType     string                 `protobuf:"bytes,3,opt,name=chain_type,json=chainType,proto3" json:"chain_type,omitempty"`
	Index         uint32                 `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	PublicKey     string                 `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletionDate  string                 `protobuf:"bytes,12,opt,name=deletion_date,json=deletionDate,proto3" json:"deletion_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletKeyMetadata) Reset() {
	*x = WalletKeyMetadata{}
	mi := &file_key_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletKeyMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletKeyMetadata) ProtoMessage() {}

func (x *WalletKeyMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletKeyMetadata.ProtoReflect.Descriptor instead.
func (*WalletKeyMetadata) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{14}
}

func (x *WalletKeyMetadata) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *WalletKeyMetadata) GetRootKeyId() string {
	if x != nil {
		return x.RootKeyId
	}
	return ""
}

func (x *WalletKeyMetadata) GetChainType() string {
	if x != nil {
		return x.ChainType
	}
	return ""
}

func (x *WalletKeyMetadata) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *WalletKeyMetadata) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *WalletKeyMetadata) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WalletKeyMetadata) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WalletKeyMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WalletKeyMetadata) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *WalletKeyMetadata) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *WalletKeyMetadata) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *WalletKeyMetadata) GetDeletionDate() string {
	if x != nil {
		return x.DeletionDate
	}
	return ""
}

var File_key_proto protoreflect.FileDescriptor

const file_key_proto_rawDesc = "" +
	"\n" +
	"\tkey.proto\x12\x11infrastructure.v1\x1a\fcommon.proto\"\xf7\x02\n" +
	"\x14CreateRootKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x12\x14\n" +
	"\x05curve\x18\x03 \x01(\tR\x05curve\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x05R\tthreshold\x12\x1f\n" +
	"\vtotal_nodes\x18\x06 \x01(\x05R\n" +
	"totalNodes\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12E\n" +
	"\x04tags\x18\t \x03(\v21.infrastructure.v1.CreateRootKeyRequest.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\x15CreateRootKeyResponse\x124\n" +
	"\x03key\x18\x01 \x01(\v2\".infrastructure.v1.RootKeyMetadataR\x03key\"*\n" +
	"\x11GetRootKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\"J\n" +
	"\x12GetRootKeyResponse\x124\n" +
	"\x03key\x18\x01 \x01(\v2\".infrastructure.v1.RootKeyMetadataR\x03key\"-\n" +
	"\x14DeleteRootKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\"s\n" +
	"\x13ListRootKeysRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12D\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2$.infrastructure.v1.PaginationRequestR\n" +
	"pagination\"\x95\x01\n" +
	"\x14ListRootKeysResponse\x126\n" +
	"\x04keys\x18\x01 \x03(\v2\".infrastructure.v1.RootKeyMetadataR\x04keys\x12E\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2%.infrastructure.v1.PaginationResponseR\n" +
	"pagination\"\x91\x02\n" +
	"\x16DeriveWalletKeyRequest\x12\x1e\n" +
	"\vroot_key_id\x18\x01 \x01(\tR\trootKeyId\x12\x1d\n" +
	"\n" +
	"chain_type\x18\x02 \x01(\tR\tchainType\x12\x14\n" +
	"\x05index\x18\x03 \x01(\rR\x05index\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12G\n" +
	"\x04tags\x18\x05 \x03(\v23.infrastructure.v1.DeriveWalletKeyRequest.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"W\n" +
	"\x17DeriveWalletKeyResponse\x12<\n" +
	"\x06wallet\x18\x01 \x01(\v2$.infrastructure.v1.WalletKeyMetadataR\x06wallet\"2\n" +
	"\x13GetWalletKeyRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"T\n" +
	"\x14GetWalletKeyResponse\x12<\n" +
	"\x06wallet\x18\x01 \x01(\v2$.infrastructure.v1.WalletKeyMetadataR\x06wallet\"\x9c\x01\n" +
	"\x15ListWalletKeysRequest\x12\x1e\n" +
	"\vroot_key_id\x18\x01 \x01(\tR\trootKeyId\x12\x1d\n" +
	"\n" +
	"chain_type\x18\x02 \x01(\tR\tchainType\x12D\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2$.infrastructure.v1.PaginationRequestR\n" +
	"pagination\"\x9f\x01\n" +
	"\x16ListWalletKeysResponse\x12>\n" +
	"\awallets\x18\x01 \x03(\v2$.infrastructure.v1.WalletKeyMetadataR\awallets\x12E\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2%.infrastructure.v1.PaginationResponseR\n" +
	"pagination\"\xee\x03\n" +
	"\x0fRootKeyMetadata\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\x12\x14\n" +
	"\x05curve\x18\x04 \x01(\tR\x05curve\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x05R\tthreshold\x12\x1f\n" +
	"\vtotal_nodes\x18\x06 \x01(\x05R\n" +
	"totalNodes\x12\x1a\n" +
	"\bprotocol\x18\a \x01(\tR\bprotocol\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12@\n" +
	"\x04tags\x18\n" +
	" \x03(\v2,.infrastructure.v1.RootKeyMetadata.TagsEntryR\x04tags\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\x12#\n" +
	"\rdeletion_date\x18\r \x01(\tR\fdeletionDate\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd8\x03\n" +
	"\x11WalletKeyMetadata\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x1e\n" +
	"\vroot_key_id\x18\x02 \x01(\tR\trootKeyId\x12\x1d\n" +
	"\n" +
	"chain_type\x18\x03 \x01(\tR\tchainType\x12\x14\n" +
	"\x05index\x18\x04 \x01(\rR\x05index\x12\x1d\n" +
	"\n" +
	"public_key\x18\x05 \x01(\tR\tpublicKey\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12B\n" +
	"\x04tags\x18\t \x03(\v2..infrastructure.v1.WalletKeyMetadata.TagsEntryR\x04tags\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\x12#\n" +
	"\rdeletion_date\x18\f \x01(\tR\fdeletionDate\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xbb\x05\n" +
	"\n" +
	"KeyService\x12b\n" +
	"\rCreateRootKey\x12'.infrastructure.v1.CreateRootKeyRequest\x1a(.infrastructure.v1.CreateRootKeyResponse\x12Y\n" +
	"\n" +
	"GetRootKey\x12$.infrastructure.v1.GetRootKeyRequest\x1a%.infrastructure.v1.GetRootKeyResponse\x12[\n" +
	"\rDeleteRootKey\x12'.infrastructure.v1.DeleteRootKeyRequest\x1a!.infrastructure.v1.StatusResponse\x12_\n" +
	"\fListRootKeys\x12&.infrastructure.v1.ListRootKeysRequest\x1a'.infrastructure.v1.ListRootKeysResponse\x12h\n" +
	"\x0fDeriveWalletKey\x12).infrastructure.v1.DeriveWalletKeyRequest\x1a*.infrastructure.v1.DeriveWalletKeyResponse\x12_\n" +
	"\fGetWalletKey\x12&.infrastructure.v1.GetWalletKeyRequest\x1a'.infrastructure.v1.GetWalletKeyResponse\x12e\n" +
	"\x0eListWalletKeys\x12(.infrastructure.v1.ListWalletKeysRequest\x1a).infrastructure.v1.ListWalletKeysResponseBBZ@github.com/kashguard/go-mpc-wallet/internal/pb/infrastructure/v1b\x06proto3"

var (
	file_key_proto_rawDescOnce sync.Once
	file_key_proto_rawDescData []byte
)

func file_key_proto_rawDescGZIP() []byte {
	file_key_proto_rawDescOnce.Do(func() {
		file_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_key_proto_rawDesc), len(file_key_proto_rawDesc)))
	})
	return file_key_proto_rawDescData
}

var file_key_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_key_proto_goTypes = []any{
	(*CreateRootKeyRequest)(nil),    // 0: infrastructure.v1.CreateRootKeyRequest
	(*CreateRootKeyResponse)(nil),   // 1: infrastructure.v1.CreateRootKeyResponse
	(*GetRootKeyRequest)(nil),       // 2: infrastructure.v1.GetRootKeyRequest
	(*GetRootKeyResponse)(nil),      // 3: infrastructure.v1.GetRootKeyResponse
	(*DeleteRootKeyRequest)(nil),    // 4: infrastructure.v1.DeleteRootKeyRequest
	(*ListRootKeysRequest)(nil),     // 5: infrastructure.v1.ListRootKeysRequest
	(*ListRootKeysResponse)(nil),    // 6: infrastructure.v1.ListRootKeysResponse
	(*DeriveWalletKeyRequest)(nil),  // 7: infrastructure.v1.DeriveWalletKeyRequest
	(*DeriveWalletKeyResponse)(nil), // 8: infrastructure.v1.DeriveWalletKeyResponse
	(*GetWalletKeyRequest)(nil),     // 9: infrastructure.v1.GetWalletKeyRequest
	(*GetWalletKeyResponse)(nil),    // 10: infrastructure.v1.GetWalletKeyResponse
	(*ListWalletKeysRequest)(nil),   // 11: infrastructure.v1.ListWalletKeysRequest
	(*ListWalletKeysResponse)(nil),  // 12: infrastructure.v1.ListWalletKeysResponse
	(*RootKeyMetadata)(nil),         // 13: infrastructure.v1.RootKeyMetadata
	(*WalletKeyMetadata)(nil),       // 14: infrastructure.v1.WalletKeyMetadata
	nil,                             // 15: infrastructure.v1.CreateRootKeyRequest.TagsEntry
	nil,                             // 16: infrastructure.v1.DeriveWalletKeyRequest.TagsEntry
	nil,                             // 17: infrastructure.v1.RootKeyMetadata.TagsEntry
	nil,                             // 18: infrastructure.v1.WalletKeyMetadata.TagsEntry
	(*PaginationRequest)(nil),       // 19: infrastructure.v1.PaginationRequest
	(*PaginationResponse)(nil),      // 20: infrastructure.v1.PaginationResponse
	(*StatusResponse)(nil),          // 21: infrastructure.v1.StatusResponse
}
var file_key_proto_depIdxs = []int32{
	15, // 0: infrastructure.v1.CreateRootKeyRequest.tags:type_name -> infrastructure.v1.CreateRootKeyRequest.TagsEntry
	13, // 1: infrastructure.v1.CreateRootKeyResponse.key:type_name -> infrastructure.v1.RootKeyMetadata
	13, // 2: infrastructure.v1.GetRootKeyResponse.key:type_name -> infrastructure.v1.RootKeyMetadata
	19, // 3: infrastructure.v1.ListRootKeysRequest.pagination:type_name -> infrastructure.v1.PaginationRequest
	13, // 4: infrastructure.v1.ListRootKeysResponse.keys:type_name -> infrastructure.v1.RootKeyMetadata
	20, // 5: infrastructure.v1.ListRootKeysResponse.pagination:type_name -> infrastructure.v1.PaginationResponse
	16, // 6: infrastructure.v1.DeriveWalletKeyRequest.tags:type_name -> infrastructure.v1.DeriveWalletKeyRequest.TagsEntry
	14, // 7: infrastructure.v1.DeriveWalletKeyResponse.wallet:type_name -> infrastructure.v1.WalletKeyMetadata
	14, // 8: infrastructure.v1.GetWalletKeyResponse.wallet:type_name -> infrastructure.v1.WalletKeyMetadata
	19, // 9: infrastructure.v1.ListWalletKeysRequest.pagination:type_name -> infrastructure.v1.PaginationRequest
	14, // 10: infrastructure.v1.ListWalletKeysResponse.wallets:type_name -> infrastructure.v1.WalletKeyMetadata
	20, // 11: infrastructure.v1.ListWalletKeysResponse.pagination:type_name -> infrastructure.v1.PaginationResponse
	17, // 12: infrastructure.v1.RootKeyMetadata.tags:type_name -> infrastructure.v1.RootKeyMetadata.TagsEntry
	18, // 13: infrastructure.v1.WalletKeyMetadata.tags:type_name -> infrastructure.v1.WalletKeyMetadata.TagsEntry
	0,  // 14: infrastructure.v1.KeyService.CreateRootKey:input_type -> infrastructure.v1.CreateRootKeyRequest
	2,  // 15: infrastructure.v1.KeyService.GetRootKey:input_type -> infrastructure.v1.GetRootKeyRequest
	4,  // 16: infrastructure.v1.KeyService.DeleteRootKey:input_type -> infrastructure.v1.DeleteRootKeyRequest
	5,  // 17: infrastructure.v1.KeyService.ListRootKeys:input_type -> infrastructure.v1.ListRootKeysRequest
	7,  // 18: infrastructure.v1.KeyService.DeriveWalletKey:input_type -> infrastructure.v1.DeriveWalletKeyRequest
	9,  // 19: infrastructure.v1.KeyService.GetWalletKey:input_type -> infrastructure.v1.GetWalletKeyRequest
	11, // 20: infrastructure.v1.KeyService.ListWalletKeys:input_type -> infrastructure.v1.ListWalletKeysRequest
	1,  // 21: infrastructure.v1.KeyService.CreateRootKey:output_type -> infrastructure.v1.CreateRootKeyResponse
	3,  // 22: infrastructure.v1.KeyService.GetRootKey:output_type -> infrastructure.v1.GetRootKeyResponse
	21, // 23: infrastructure.v1.KeyService.DeleteRootKey:output_type -> infrastructure.v1.StatusResponse
	6,  // 24: infrastructure.v1.KeyService.ListRootKeys:output_type -> infrastructure.v1.ListRootKeysResponse
	8,  // 25: infrastructure.v1.KeyService.DeriveWalletKey:output_type -> infrastructure.v1.DeriveWalletKeyResponse
	10, // 26: infrastructure.v1.KeyService.GetWalletKey:output_type -> infrastructure.v1.GetWalletKeyResponse
	12, // 27: infrastructure.v1.KeyService.ListWalletKeys:output_type -> infrastructure.v1.ListWalletKeysResponse
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_key_proto_init() }
func file_key_proto_init() {
	if File_key_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_key_proto_rawDesc), len(file_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_key_proto_goTypes,
		DependencyIndexes: file_key_proto_depIdxs,
		MessageInfos:      file_key_proto_msgTypes,
	}.Build()
	File_key_proto = out.File
	file_key_proto_goTypes = nil
	file_key_proto_depIdxs = nil
}
