// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.4
// source: key.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyService_CreateRootKey_FullMethodName   = "/infrastructure.v1.KeyService/CreateRootKey"
	KeyService_GetRootKey_FullMethodName      = "/infrastructure.v1.KeyService/GetRootKey"
	KeyService_DeleteRootKey_FullMethodName   = "/infrastructure.v1.KeyService/DeleteRootKey"
	KeyService_ListRootKeys_FullMethodName    = "/infrastructure.v1.KeyService/ListRootKeys"
	KeyService_DeriveWalletKey_FullMethodName = "/infrastructure.v1.KeyService/DeriveWalletKey"
	KeyService_GetWalletKey_FullMethodName    = "/infrastructure.v1.KeyService/GetWalletKey"
	KeyService_ListWalletKeys_FullMethodName  = "/infrastructure.v1.KeyService/ListWalletKeys"
)

// KeyServiceClient is the client API for KeyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KeyService 密钥服务
type KeyServiceClient interface {
	// 创建根密钥（执行DKG，2-of-3模式）
	CreateRootKey(ctx context.Context, in *CreateRootKeyRequest, opts ...grpc.CallOption) (*CreateRootKeyResponse, error)
	// 获取根密钥信息
	GetRootKey(ctx context.Context, in *GetRootKeyRequest, opts ...grpc.CallOption) (*GetRootKeyResponse, error)
	// 删除根密钥
	DeleteRootKey(ctx context.Context, in *DeleteRootKeyRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// 列出根密钥
	ListRootKeys(ctx context.Context, in *ListRootKeysRequest, opts ...grpc.CallOption) (*ListRootKeysResponse, error)
	// 派生钱包密钥（Hardened Derivation）
	DeriveWalletKey(ctx context.Context, in *DeriveWalletKeyRequest, opts ...grpc.CallOption) (*DeriveWalletKeyResponse, error)
	// 获取钱包密钥信息
	GetWalletKey(ctx context.Context, in *GetWalletKeyRequest, opts ...grpc.CallOption) (*GetWalletKeyResponse, error)
	// 列出钱包密钥
	ListWalletKeys(ctx context.Context, in *ListWalletKeysRequest, opts ...grpc.CallOption) (*ListWalletKeysResponse, error)
}

type keyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyServiceClient(cc grpc.ClientConnInterface) KeyServiceClient {
	return &keyServiceClient{cc}
}

func (c *keyServiceClient) CreateRootKey(ctx context.Context, in *CreateRootKeyRequest, opts ...grpc.CallOption) (*CreateRootKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRootKeyResponse)
	err := c.cc.Invoke(ctx, KeyService_CreateRootKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) GetRootKey(ctx context.Context, in *GetRootKeyRequest, opts ...grpc.CallOption) (*GetRootKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRootKeyResponse)
	err := c.cc.Invoke(ctx, KeyService_GetRootKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) DeleteRootKey(ctx context.Context, in *DeleteRootKeyRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, KeyService_DeleteRootKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) ListRootKeys(ctx context.Context, in *ListRootKeysRequest, opts ...grpc.CallOption) (*ListRootKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRootKeysResponse)
	err := c.cc.Invoke(ctx, KeyService_ListRootKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) DeriveWalletKey(ctx context.Context, in *DeriveWalletKeyRequest, opts ...grpc.CallOption) (*DeriveWalletKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeriveWalletKeyResponse)
	err := c.cc.Invoke(ctx, KeyService_DeriveWalletKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) GetWalletKey(ctx context.Context, in *GetWalletKeyRequest, opts ...grpc.CallOption) (*GetWalletKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletKeyResponse)
	err := c.cc.Invoke(ctx, KeyService_GetWalletKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) ListWalletKeys(ctx context.Context, in *ListWalletKeysRequest, opts ...grpc.CallOption) (*ListWalletKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWalletKeysResponse)
	err := c.cc.Invoke(ctx, KeyService_ListWalletKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyServiceServer is the server API for KeyService service.
// All implementations must embed UnimplementedKeyServiceServer
// for forward compatibility.
//
// KeyService 密钥服务
type KeyServiceServer interface {
	// 创建根密钥（执行DKG，2-of-3模式）
	CreateRootKey(context.Context, *CreateRootKeyRequest) (*CreateRootKeyResponse, error)
	// 获取根密钥信息
	GetRootKey(context.Context, *GetRootKeyRequest) (*GetRootKeyResponse, error)
	// 删除根密钥
	DeleteRootKey(context.Context, *DeleteRootKeyRequest) (*StatusResponse, error)
	// 列出根密钥
	ListRootKeys(context.Context, *ListRootKeysRequest) (*ListRootKeysResponse, error)
	// 派生钱包密钥（Hardened Derivation）
	DeriveWalletKey(context.Context, *DeriveWalletKeyRequest) (*DeriveWalletKeyResponse, error)
	// 获取钱包密钥信息
	GetWalletKey(context.Context, *GetWalletKeyRequest) (*GetWalletKeyResponse, error)
	// 列出钱包密钥
	ListWalletKeys(context.Context, *ListWalletKeysRequest) (*ListWalletKeysResponse, error)
	mustEmbedUnimplementedKeyServiceServer()
}

// UnimplementedKeyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyServiceServer struct{}

func (UnimplementedKeyServiceServer) CreateRootKey(context.Context, *CreateRootKeyRequest) (*CreateRootKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRootKey not implemented")
}
func (UnimplementedKeyServiceServer) GetRootKey(context.Context, *GetRootKeyRequest) (*GetRootKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRootKey not implemented")
}
func (UnimplementedKeyServiceServer) DeleteRootKey(context.Context, *DeleteRootKeyRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRootKey not implemented")
}
func (UnimplementedKeyServiceServer) ListRootKeys(context.Context, *ListRootKeysRequest) (*ListRootKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRootKeys not implemented")
}
func (UnimplementedKeyServiceServer) DeriveWalletKey(context.Context, *DeriveWalletKeyRequest) (*DeriveWalletKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeriveWalletKey not implemented")
}
func (UnimplementedKeyServiceServer) GetWalletKey(context.Context, *GetWalletKeyRequest) (*GetWalletKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWalletKey not implemented")
}
func (UnimplementedKeyServiceServer) ListWalletKeys(context.Context, *ListWalletKeysRequest) (*ListWalletKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWalletKeys not implemented")
}
func (UnimplementedKeyServiceServer) mustEmbedUnimplementedKeyServiceServer() {}
func (UnimplementedKeyServiceServer) testEmbeddedByValue()                    {}

// UnsafeKeyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyServiceServer will
// result in compilation errors.
type UnsafeKeyServiceServer interface {
	mustEmbedUnimplementedKeyServiceServer()
}

func RegisterKeyServiceServer(s grpc.ServiceRegistrar, srv KeyServiceServer) {
	// If the following call panics, it indicates UnimplementedKeyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyService_ServiceDesc, srv)
}

func _KeyService_CreateRootKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRootKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).CreateRootKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_CreateRootKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).CreateRootKey(ctx, req.(*CreateRootKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_GetRootKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRootKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).GetRootKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_GetRootKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).GetRootKey(ctx, req.(*GetRootKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_DeleteRootKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRootKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).DeleteRootKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_DeleteRootKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).DeleteRootKey(ctx, req.(*DeleteRootKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_ListRootKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRootKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).ListRootKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_ListRootKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).ListRootKeys(ctx, req.(*ListRootKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_DeriveWalletKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeriveWalletKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).DeriveWalletKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_DeriveWalletKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).DeriveWalletKey(ctx, req.(*DeriveWalletKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_GetWalletKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).GetWalletKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_GetWalletKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).GetWalletKey(ctx, req.(*GetWalletKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_ListWalletKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWalletKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).ListWalletKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_ListWalletKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).ListWalletKeys(ctx, req.(*ListWalletKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyService_ServiceDesc is the grpc.ServiceDesc for KeyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infrastructure.v1.KeyService",
	HandlerType: (*KeyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRootKey",
			Handler:    _KeyService_CreateRootKey_Handler,
		},
		{
			MethodName: "GetRootKey",
			Handler:    _KeyService_GetRootKey_Handler,
		},
		{
			MethodName: "DeleteRootKey",
			Handler:    _KeyService_DeleteRootKey_Handler,
		},
		{
			MethodName: "ListRootKeys",
			Handler:    _KeyService_ListRootKeys_Handler,
		},
		{
			MethodName: "DeriveWalletKey",
			Handler:    _KeyService_DeriveWalletKey_Handler,
		},
		{
			MethodName: "GetWalletKey",
			Handler:    _KeyService_GetWalletKey_Handler,
		},
		{
			MethodName: "ListWalletKeys",
			Handler:    _KeyService_ListWalletKeys_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "key.proto",
}
