// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: signing.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateSigningSessionRequest 创建签名会话请求
type CreateSigningSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"` // gg18, gg20, frost
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSigningSessionRequest) Reset() {
	*x = CreateSigningSessionRequest{}
	mi := &file_signing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSigningSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSigningSessionRequest) ProtoMessage() {}

func (x *CreateSigningSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSigningSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSigningSessionRequest) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSigningSessionRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *CreateSigningSessionRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

// CreateSigningSessionResponse 创建签名会话响应
type CreateSigningSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SigningSession        `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSigningSessionResponse) Reset() {
	*x = CreateSigningSessionResponse{}
	mi := &file_signing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSigningSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSigningSessionResponse) ProtoMessage() {}

func (x *CreateSigningSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSigningSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSigningSessionResponse) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSigningSessionResponse) GetSession() *SigningSession {
	if x != nil {
		return x.Session
	}
	return nil
}

// ThresholdSignRequest 阈值签名请求
type ThresholdSignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Message       []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MessageHex    string                 `protobuf:"bytes,3,opt,name=message_hex,json=messageHex,proto3" json:"message_hex,omitempty"`
	ChainType     string                 `protobuf:"bytes,4,opt,name=chain_type,json=chainType,proto3" json:"chain_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThresholdSignRequest) Reset() {
	*x = ThresholdSignRequest{}
	mi := &file_signing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThresholdSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThresholdSignRequest) ProtoMessage() {}

func (x *ThresholdSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThresholdSignRequest.ProtoReflect.Descriptor instead.
func (*ThresholdSignRequest) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{2}
}

func (x *ThresholdSignRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ThresholdSignRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ThresholdSignRequest) GetMessageHex() string {
	if x != nil {
		return x.MessageHex
	}
	return ""
}

func (x *ThresholdSignRequest) GetChainType() string {
	if x != nil {
		return x.ChainType
	}
	return ""
}

// ThresholdSignResponse 阈值签名响应
type ThresholdSignResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Signature          string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	KeyId              string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	PublicKey          string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Message            string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	ChainType          string                 `protobuf:"bytes,5,opt,name=chain_type,json=chainType,proto3" json:"chain_type,omitempty"`
	SessionId          string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SignedAt           string                 `protobuf:"bytes,7,opt,name=signed_at,json=signedAt,proto3" json:"signed_at,omitempty"`
	ParticipatingNodes []string               `protobuf:"bytes,8,rep,name=participating_nodes,json=participatingNodes,proto3" json:"participating_nodes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ThresholdSignResponse) Reset() {
	*x = ThresholdSignResponse{}
	mi := &file_signing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThresholdSignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThresholdSignResponse) ProtoMessage() {}

func (x *ThresholdSignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThresholdSignResponse.ProtoReflect.Descriptor instead.
func (*ThresholdSignResponse) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{3}
}

func (x *ThresholdSignResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ThresholdSignResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ThresholdSignResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *ThresholdSignResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ThresholdSignResponse) GetChainType() string {
	if x != nil {
		return x.ChainType
	}
	return ""
}

func (x *ThresholdSignResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ThresholdSignResponse) GetSignedAt() string {
	if x != nil {
		return x.SignedAt
	}
	return ""
}

func (x *ThresholdSignResponse) GetParticipatingNodes() []string {
	if x != nil {
		return x.ParticipatingNodes
	}
	return nil
}

// GetSigningSessionRequest 获取签名会话请求
type GetSigningSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSigningSessionRequest) Reset() {
	*x = GetSigningSessionRequest{}
	mi := &file_signing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSigningSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSigningSessionRequest) ProtoMessage() {}

func (x *GetSigningSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSigningSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSigningSessionRequest) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{4}
}

func (x *GetSigningSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// GetSigningSessionResponse 获取签名会话响应
type GetSigningSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SigningSession        `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSigningSessionResponse) Reset() {
	*x = GetSigningSessionResponse{}
	mi := &file_signing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSigningSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSigningSessionResponse) ProtoMessage() {}

func (x *GetSigningSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSigningSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSigningSessionResponse) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{5}
}

func (x *GetSigningSessionResponse) GetSession() *SigningSession {
	if x != nil {
		return x.Session
	}
	return nil
}

// BatchSignRequest 批量签名请求
type BatchSignRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Messages      []*ThresholdSignRequest `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSignRequest) Reset() {
	*x = BatchSignRequest{}
	mi := &file_signing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSignRequest) ProtoMessage() {}

func (x *BatchSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSignRequest.ProtoReflect.Descriptor instead.
func (*BatchSignRequest) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{6}
}

func (x *BatchSignRequest) GetMessages() []*ThresholdSignRequest {
	if x != nil {
		return x.Messages
	}
	return nil
}

// BatchSignResponse 批量签名响应
type BatchSignResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Signatures    []*ThresholdSignResponse `protobuf:"bytes,1,rep,name=signatures,proto3" json:"signatures,omitempty"`
	Total         int32                    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Success       int32                    `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Failed        int32                    `protobuf:"varint,4,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSignResponse) Reset() {
	*x = BatchSignResponse{}
	mi := &file_signing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSignResponse) ProtoMessage() {}

func (x *BatchSignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSignResponse.ProtoReflect.Descriptor instead.
func (*BatchSignResponse) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{7}
}

func (x *BatchSignResponse) GetSignatures() []*ThresholdSignResponse {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *BatchSignResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BatchSignResponse) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *BatchSignResponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

// VerifySignatureRequest 验证签名请求
type VerifySignatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Message       []byte                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	MessageHex    string                 `protobuf:"bytes,4,opt,name=message_hex,json=messageHex,proto3" json:"message_hex,omitempty"`
	ChainType     string                 `protobuf:"bytes,5,opt,name=chain_type,json=chainType,proto3" json:"chain_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySignatureRequest) Reset() {
	*x = VerifySignatureRequest{}
	mi := &file_signing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySignatureRequest) ProtoMessage() {}

func (x *VerifySignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySignatureRequest.ProtoReflect.Descriptor instead.
func (*VerifySignatureRequest) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{8}
}

func (x *VerifySignatureRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *VerifySignatureRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *VerifySignatureRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *VerifySignatureRequest) GetMessageHex() string {
	if x != nil {
		return x.MessageHex
	}
	return ""
}

func (x *VerifySignatureRequest) GetChainType() string {
	if x != nil {
		return x.ChainType
	}
	return ""
}

// VerifySignatureResponse 验证签名响应
type VerifySignatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	VerifiedAt    string                 `protobuf:"bytes,4,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySignatureResponse) Reset() {
	*x = VerifySignatureResponse{}
	mi := &file_signing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySignatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySignatureResponse) ProtoMessage() {}

func (x *VerifySignatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySignatureResponse.ProtoReflect.Descriptor instead.
func (*VerifySignatureResponse) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{9}
}

func (x *VerifySignatureResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifySignatureResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *VerifySignatureResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *VerifySignatureResponse) GetVerifiedAt() string {
	if x != nil {
		return x.VerifiedAt
	}
	return ""
}

// SigningSession 签名会话
type SigningSession struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionId          string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	KeyId              string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Protocol           string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Status             string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Threshold          int32                  `protobuf:"varint,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	TotalNodes         int32                  `protobuf:"varint,6,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	ParticipatingNodes []string               `protobuf:"bytes,7,rep,name=participating_nodes,json=participatingNodes,proto3" json:"participating_nodes,omitempty"`
	CurrentRound       int32                  `protobuf:"varint,8,opt,name=current_round,json=currentRound,proto3" json:"current_round,omitempty"`
	TotalRounds        int32                  `protobuf:"varint,9,opt,name=total_rounds,json=totalRounds,proto3" json:"total_rounds,omitempty"`
	Signature          string                 `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt        string                 `protobuf:"bytes,12,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	DurationMs         int32                  `protobuf:"varint,13,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SigningSession) Reset() {
	*x = SigningSession{}
	mi := &file_signing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningSession) ProtoMessage() {}

func (x *SigningSession) ProtoReflect() protoreflect.Message {
	mi := &file_signing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningSession.ProtoReflect.Descriptor instead.
func (*SigningSession) Descriptor() ([]byte, []int) {
	return file_signing_proto_rawDescGZIP(), []int{10}
}

func (x *SigningSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SigningSession) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SigningSession) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *SigningSession) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SigningSession) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *SigningSession) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *SigningSession) GetParticipatingNodes() []string {
	if x != nil {
		return x.ParticipatingNodes
	}
	return nil
}

func (x *SigningSession) GetCurrentRound() int32 {
	if x != nil {
		return x.CurrentRound
	}
	return 0
}

func (x *SigningSession) GetTotalRounds() int32 {
	if x != nil {
		return x.TotalRounds
	}
	return 0
}

func (x *SigningSession) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SigningSession) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SigningSession) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *SigningSession) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

var File_signing_proto protoreflect.FileDescriptor

const file_signing_proto_rawDesc = "" +
	"\n" +
	"\rsigning.proto\x12\x11infrastructure.v1\x1a\fcommon.proto\"P\n" +
	"\x1bCreateSigningSessionRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\"[\n" +
	"\x1cCreateSigningSessionResponse\x12;\n" +
	"\asession\x18\x01 \x01(\v2!.infrastructure.v1.SigningSessionR\asession\"\x87\x01\n" +
	"\x14ThresholdSignRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\x12\x1f\n" +
	"\vmessage_hex\x18\x03 \x01(\tR\n" +
	"messageHex\x12\x1d\n" +
	"\n" +
	"chain_type\x18\x04 \x01(\tR\tchainType\"\x91\x02\n" +
	"\x15ThresholdSignResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"chain_type\x18\x05 \x01(\tR\tchainType\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tsigned_at\x18\a \x01(\tR\bsignedAt\x12/\n" +
	"\x13participating_nodes\x18\b \x03(\tR\x12participatingNodes\"9\n" +
	"\x18GetSigningSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"X\n" +
	"\x19GetSigningSessionResponse\x12;\n" +
	"\asession\x18\x01 \x01(\v2!.infrastructure.v1.SigningSessionR\asession\"W\n" +
	"\x10BatchSignRequest\x12C\n" +
	"\bmessages\x18\x01 \x03(\v2'.infrastructure.v1.ThresholdSignRequestR\bmessages\"\xa5\x01\n" +
	"\x11BatchSignResponse\x12H\n" +
	"\n" +
	"signatures\x18\x01 \x03(\v2(.infrastructure.v1.ThresholdSignResponseR\n" +
	"signatures\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\x05R\asuccess\x12\x16\n" +
	"\x06failed\x18\x04 \x01(\x05R\x06failed\"\xaf\x01\n" +
	"\x16VerifySignatureRequest\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x18\n" +
	"\amessage\x18\x03 \x01(\fR\amessage\x12\x1f\n" +
	"\vmessage_hex\x18\x04 \x01(\tR\n" +
	"messageHex\x12\x1d\n" +
	"\n" +
	"chain_type\x18\x05 \x01(\tR\tchainType\"\x89\x01\n" +
	"\x17VerifySignatureResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1f\n" +
	"\vverified_at\x18\x04 \x01(\tR\n" +
	"verifiedAt\"\xb3\x03\n" +
	"\x0eSigningSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x05R\tthreshold\x12\x1f\n" +
	"\vtotal_nodes\x18\x06 \x01(\x05R\n" +
	"totalNodes\x12/\n" +
	"\x13participating_nodes\x18\a \x03(\tR\x12participatingNodes\x12#\n" +
	"\rcurrent_round\x18\b \x01(\x05R\fcurrentRound\x12!\n" +
	"\ftotal_rounds\x18\t \x01(\x05R\vtotalRounds\x12\x1c\n" +
	"\tsignature\x18\n" +
	" \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12!\n" +
	"\fcompleted_at\x18\f \x01(\tR\vcompletedAt\x12\x1f\n" +
	"\vduration_ms\x18\r \x01(\x05R\n" +
	"durationMs2\x9f\x04\n" +
	"\x0eSigningService\x12w\n" +
	"\x14CreateSigningSession\x12..infrastructure.v1.CreateSigningSessionRequest\x1a/.infrastructure.v1.CreateSigningSessionResponse\x12b\n" +
	"\rThresholdSign\x12'.infrastructure.v1.ThresholdSignRequest\x1a(.infrastructure.v1.ThresholdSignResponse\x12n\n" +
	"\x11GetSigningSession\x12+.infrastructure.v1.GetSigningSessionRequest\x1a,.infrastructure.v1.GetSigningSessionResponse\x12V\n" +
	"\tBatchSign\x12#.infrastructure.v1.BatchSignRequest\x1a$.infrastructure.v1.BatchSignResponse\x12h\n" +
	"\x0fVerifySignature\x12).infrastructure.v1.VerifySignatureRequest\x1a*.infrastructure.v1.VerifySignatureResponseBBZ@github.com/kashguard/go-mpc-wallet/internal/pb/infrastructure/v1b\x06proto3"

var (
	file_signing_proto_rawDescOnce sync.Once
	file_signing_proto_rawDescData []byte
)

func file_signing_proto_rawDescGZIP() []byte {
	file_signing_proto_rawDescOnce.Do(func() {
		file_signing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signing_proto_rawDesc), len(file_signing_proto_rawDesc)))
	})
	return file_signing_proto_rawDescData
}

var file_signing_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_signing_proto_goTypes = []any{
	(*CreateSigningSessionRequest)(nil),  // 0: infrastructure.v1.CreateSigningSessionRequest
	(*CreateSigningSessionResponse)(nil), // 1: infrastructure.v1.CreateSigningSessionResponse
	(*ThresholdSignRequest)(nil),         // 2: infrastructure.v1.ThresholdSignRequest
	(*ThresholdSignResponse)(nil),        // 3: infrastructure.v1.ThresholdSignResponse
	(*GetSigningSessionRequest)(nil),     // 4: infrastructure.v1.GetSigningSessionRequest
	(*GetSigningSessionResponse)(nil),    // 5: infrastructure.v1.GetSigningSessionResponse
	(*BatchSignRequest)(nil),             // 6: infrastructure.v1.BatchSignRequest
	(*BatchSignResponse)(nil),            // 7: infrastructure.v1.BatchSignResponse
	(*VerifySignatureRequest)(nil),       // 8: infrastructure.v1.VerifySignatureRequest
	(*VerifySignatureResponse)(nil),      // 9: infrastructure.v1.VerifySignatureResponse
	(*SigningSession)(nil),               // 10: infrastructure.v1.SigningSession
}
var file_signing_proto_depIdxs = []int32{
	10, // 0: infrastructure.v1.CreateSigningSessionResponse.session:type_name -> infrastructure.v1.SigningSession
	10, // 1: infrastructure.v1.GetSigningSessionResponse.session:type_name -> infrastructure.v1.SigningSession
	2,  // 2: infrastructure.v1.BatchSignRequest.messages:type_name -> infrastructure.v1.ThresholdSignRequest
	3,  // 3: infrastructure.v1.BatchSignResponse.signatures:type_name -> infrastructure.v1.ThresholdSignResponse
	0,  // 4: infrastructure.v1.SigningService.CreateSigningSession:input_type -> infrastructure.v1.CreateSigningSessionRequest
	2,  // 5: infrastructure.v1.SigningService.ThresholdSign:input_type -> infrastructure.v1.ThresholdSignRequest
	4,  // 6: infrastructure.v1.SigningService.GetSigningSession:input_type -> infrastructure.v1.GetSigningSessionRequest
	6,  // 7: infrastructure.v1.SigningService.BatchSign:input_type -> infrastructure.v1.BatchSignRequest
	8,  // 8: infrastructure.v1.SigningService.VerifySignature:input_type -> infrastructure.v1.VerifySignatureRequest
	1,  // 9: infrastructure.v1.SigningService.CreateSigningSession:output_type -> infrastructure.v1.CreateSigningSessionResponse
	3,  // 10: infrastructure.v1.SigningService.ThresholdSign:output_type -> infrastructure.v1.ThresholdSignResponse
	5,  // 11: infrastructure.v1.SigningService.GetSigningSession:output_type -> infrastructure.v1.GetSigningSessionResponse
	7,  // 12: infrastructure.v1.SigningService.BatchSign:output_type -> infrastructure.v1.BatchSignResponse
	9,  // 13: infrastructure.v1.SigningService.VerifySignature:output_type -> infrastructure.v1.VerifySignatureResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_signing_proto_init() }
func file_signing_proto_init() {
	if File_signing_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signing_proto_rawDesc), len(file_signing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_signing_proto_goTypes,
		DependencyIndexes: file_signing_proto_depIdxs,
		MessageInfos:      file_signing_proto_msgTypes,
	}.Build()
	File_signing_proto = out.File
	file_signing_proto_goTypes = nil
	file_signing_proto_depIdxs = nil
}
