// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.4
// source: signing.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SigningService_CreateSigningSession_FullMethodName = "/infrastructure.v1.SigningService/CreateSigningSession"
	SigningService_ThresholdSign_FullMethodName        = "/infrastructure.v1.SigningService/ThresholdSign"
	SigningService_GetSigningSession_FullMethodName    = "/infrastructure.v1.SigningService/GetSigningSession"
	SigningService_BatchSign_FullMethodName            = "/infrastructure.v1.SigningService/BatchSign"
	SigningService_VerifySignature_FullMethodName      = "/infrastructure.v1.SigningService/VerifySignature"
)

// SigningServiceClient is the client API for SigningService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SigningService 签名服务
type SigningServiceClient interface {
	// 创建签名会话
	CreateSigningSession(ctx context.Context, in *CreateSigningSessionRequest, opts ...grpc.CallOption) (*CreateSigningSessionResponse, error)
	// 阈值签名（2-of-3，仅服务器分片参与）
	ThresholdSign(ctx context.Context, in *ThresholdSignRequest, opts ...grpc.CallOption) (*ThresholdSignResponse, error)
	// 获取签名会话
	GetSigningSession(ctx context.Context, in *GetSigningSessionRequest, opts ...grpc.CallOption) (*GetSigningSessionResponse, error)
	// 批量签名
	BatchSign(ctx context.Context, in *BatchSignRequest, opts ...grpc.CallOption) (*BatchSignResponse, error)
	// 验证签名
	VerifySignature(ctx context.Context, in *VerifySignatureRequest, opts ...grpc.CallOption) (*VerifySignatureResponse, error)
}

type signingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSigningServiceClient(cc grpc.ClientConnInterface) SigningServiceClient {
	return &signingServiceClient{cc}
}

func (c *signingServiceClient) CreateSigningSession(ctx context.Context, in *CreateSigningSessionRequest, opts ...grpc.CallOption) (*CreateSigningSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSigningSessionResponse)
	err := c.cc.Invoke(ctx, SigningService_CreateSigningSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signingServiceClient) ThresholdSign(ctx context.Context, in *ThresholdSignRequest, opts ...grpc.CallOption) (*ThresholdSignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThresholdSignResponse)
	err := c.cc.Invoke(ctx, SigningService_ThresholdSign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signingServiceClient) GetSigningSession(ctx context.Context, in *GetSigningSessionRequest, opts ...grpc.CallOption) (*GetSigningSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSigningSessionResponse)
	err := c.cc.Invoke(ctx, SigningService_GetSigningSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signingServiceClient) BatchSign(ctx context.Context, in *BatchSignRequest, opts ...grpc.CallOption) (*BatchSignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchSignResponse)
	err := c.cc.Invoke(ctx, SigningService_BatchSign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signingServiceClient) VerifySignature(ctx context.Context, in *VerifySignatureRequest, opts ...grpc.CallOption) (*VerifySignatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifySignatureResponse)
	err := c.cc.Invoke(ctx, SigningService_VerifySignature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SigningServiceServer is the server API for SigningService service.
// All implementations must embed UnimplementedSigningServiceServer
// for forward compatibility.
//
// SigningService 签名服务
type SigningServiceServer interface {
	// 创建签名会话
	CreateSigningSession(context.Context, *CreateSigningSessionRequest) (*CreateSigningSessionResponse, error)
	// 阈值签名（2-of-3，仅服务器分片参与）
	ThresholdSign(context.Context, *ThresholdSignRequest) (*ThresholdSignResponse, error)
	// 获取签名会话
	GetSigningSession(context.Context, *GetSigningSessionRequest) (*GetSigningSessionResponse, error)
	// 批量签名
	BatchSign(context.Context, *BatchSignRequest) (*BatchSignResponse, error)
	// 验证签名
	VerifySignature(context.Context, *VerifySignatureRequest) (*VerifySignatureResponse, error)
	mustEmbedUnimplementedSigningServiceServer()
}

// UnimplementedSigningServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSigningServiceServer struct{}

func (UnimplementedSigningServiceServer) CreateSigningSession(context.Context, *CreateSigningSessionRequest) (*CreateSigningSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSigningSession not implemented")
}
func (UnimplementedSigningServiceServer) ThresholdSign(context.Context, *ThresholdSignRequest) (*ThresholdSignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ThresholdSign not implemented")
}
func (UnimplementedSigningServiceServer) GetSigningSession(context.Context, *GetSigningSessionRequest) (*GetSigningSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSigningSession not implemented")
}
func (UnimplementedSigningServiceServer) BatchSign(context.Context, *BatchSignRequest) (*BatchSignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchSign not implemented")
}
func (UnimplementedSigningServiceServer) VerifySignature(context.Context, *VerifySignatureRequest) (*VerifySignatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifySignature not implemented")
}
func (UnimplementedSigningServiceServer) mustEmbedUnimplementedSigningServiceServer() {}
func (UnimplementedSigningServiceServer) testEmbeddedByValue()                        {}

// UnsafeSigningServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SigningServiceServer will
// result in compilation errors.
type UnsafeSigningServiceServer interface {
	mustEmbedUnimplementedSigningServiceServer()
}

func RegisterSigningServiceServer(s grpc.ServiceRegistrar, srv SigningServiceServer) {
	// If the following call panics, it indicates UnimplementedSigningServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SigningService_ServiceDesc, srv)
}

func _SigningService_CreateSigningSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSigningSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigningServiceServer).CreateSigningSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SigningService_CreateSigningSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigningServiceServer).CreateSigningSession(ctx, req.(*CreateSigningSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SigningService_ThresholdSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThresholdSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigningServiceServer).ThresholdSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SigningService_ThresholdSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigningServiceServer).ThresholdSign(ctx, req.(*ThresholdSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SigningService_GetSigningSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSigningSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigningServiceServer).GetSigningSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SigningService_GetSigningSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigningServiceServer).GetSigningSession(ctx, req.(*GetSigningSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SigningService_BatchSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigningServiceServer).BatchSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SigningService_BatchSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigningServiceServer).BatchSign(ctx, req.(*BatchSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SigningService_VerifySignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigningServiceServer).VerifySignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SigningService_VerifySignature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigningServiceServer).VerifySignature(ctx, req.(*VerifySignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SigningService_ServiceDesc is the grpc.ServiceDesc for SigningService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SigningService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infrastructure.v1.SigningService",
	HandlerType: (*SigningServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSigningSession",
			Handler:    _SigningService_CreateSigningSession_Handler,
		},
		{
			MethodName: "ThresholdSign",
			Handler:    _SigningService_ThresholdSign_Handler,
		},
		{
			MethodName: "GetSigningSession",
			Handler:    _SigningService_GetSigningSession_Handler,
		},
		{
			MethodName: "BatchSign",
			Handler:    _SigningService_BatchSign_Handler,
		},
		{
			MethodName: "VerifySignature",
			Handler:    _SigningService_VerifySignature_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "signing.proto",
}
