// Code generated by go run -tags scripts scripts/handlers/gen_handlers.go; DO NOT EDIT.
package handlers

import (
	"github.com/kashguard/go-mpc-wallet/internal/api"
	"github.com/kashguard/go-mpc-wallet/internal/api/handlers/auth"
	"github.com/kashguard/go-mpc-wallet/internal/api/handlers/common"
	"github.com/kashguard/go-mpc-wallet/internal/api/handlers/mpc/keys"
	// "github.com/kashguard/go-mpc-wallet/internal/api/handlers/mpc/nodes"
	"github.com/kashguard/go-mpc-wallet/internal/api/handlers/mpc/sessions"
	"github.com/kashguard/go-mpc-wallet/internal/api/handlers/mpc/signing"
	"github.com/kashguard/go-mpc-wallet/internal/api/handlers/push"
	"github.com/kashguard/go-mpc-wallet/internal/api/handlers/wellknown"
	"github.com/labstack/echo/v4"
)

func AttachAllRoutes(s *api.Server) {
	// attach our routes
	s.Router.Routes = []*echo.Route{
		auth.DeleteUserAccountRoute(s),
		auth.GetCompleteRegisterRoute(s),
		auth.GetUserInfoRoute(s),
		auth.PostChangePasswordRoute(s),
		auth.PostCompleteRegisterRoute(s),
		auth.PostForgotPasswordCompleteRoute(s),
		auth.PostForgotPasswordRoute(s),
		auth.PostLoginRoute(s),
		auth.PostLogoutRoute(s),
		auth.PostRefreshRoute(s),
		auth.PostRegisterRoute(s),
		common.GetHealthyRoute(s),
		common.GetReadyRoute(s),
		common.GetSwaggerRoute(s),
		common.GetVersionRoute(s),
		keys.DeleteKeyRoute(s),
		keys.GetKeyRoute(s),
		keys.GetListKeysRoute(s),
		keys.PostCreateKeyRoute(s),
		keys.PostGenerateAddressRoute(s),
		// nodes.GetListNodesRoute(s),
		// nodes.GetNodeHealthRoute(s),
		// nodes.GetNodeRoute(s),
		// nodes.PostRegisterNodeRoute(s),
		sessions.GetSessionRoute(s),
		sessions.PostCancelSessionRoute(s),
		sessions.PostCreateSessionRoute(s),
		sessions.PostJoinSessionRoute(s),
		signing.PostBatchSignRoute(s),
		signing.PostSignRoute(s),
		signing.PostVerifyRoute(s),
		push.PutUpdatePushTokenRoute(s),
		wellknown.GetAndroidDigitalAssetLinksRoute(s),
		wellknown.GetAppleAppSiteAssociationRoute(s),
	}
}
